package Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1100422815
 */
import java.awt.*;
import java.awt.event.*;
import java.awt.font.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
 
import javax.swing.*;

public class FrmAdmin extends javax.swing.JFrame {

    //Create an instance of the class Queries
    //Queries query;
    //New instance of CardLayout
    CardLayout card = new CardLayout();
    PopUpMsgBox msgbox = new PopUpMsgBox();
    Queries query = new Queries();
    ResultSet rs;
    FrmAdmin admin;
    FrmAdminConfig config;
    /**
     * Creates new form form
     */
    public FrmAdmin() {
        
        initComponents();
        //CONNECTION PARAMETERS SETTINGS
        //db = new Database();
        query.setUser("root");
        query.setPassword("");
        query.setHost("localhost");
        query.setPort("3306");
        query.setDatabase("findmycareer");
        //SET THE OPTION DIALOG BOX
        //
        //Sets the JFrame invisible so the JDialogbox can appear without having the form visible underneath
        this.setVisible(false);
        this.CbxSections.addItem(null);
        this.CbxSections.setSelectedItem(null);
        //SET THE JFRAME
        //
        this.BtnExit_FrmAdmin.requestFocusInWindow();
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupSetOption = new javax.swing.ButtonGroup();
        BtnExit_FrmAdmin = new javax.swing.JButton();
        PanelMainCards_FrmAdmin = new javax.swing.JPanel();
        PanelDbUpdate = new javax.swing.JPanel();
        CbxOption = new javax.swing.JComboBox();
        LblOptions = new javax.swing.JLabel();
        CbxSections = new javax.swing.JComboBox();
        LblSections = new javax.swing.JLabel();
        LblOptionName = new javax.swing.JLabel();
        TxtOption = new javax.swing.JTextField();
        LblOptionDescr = new javax.swing.JLabel();
        ScrlPaneCatDescr_PanelCategory = new javax.swing.JScrollPane();
        TxtOptionDescr = new javax.swing.JTextArea();
        BtnAction = new javax.swing.JButton();
        LblAction = new javax.swing.JLabel();
        CbxAction = new javax.swing.JComboBox();
        PanelUserParameters = new javax.swing.JPanel();
        LblSelectedParams = new javax.swing.JLabel();
        PanelAge = new javax.swing.JPanel();
        TxtAgeGreaterThan = new javax.swing.JTextField();
        LblAgeRange = new javax.swing.JLabel();
        TxtAgeValue2 = new javax.swing.JTextField();
        LblAgeEqualTo = new javax.swing.JLabel();
        TxtAgeEqualTo = new javax.swing.JTextField();
        LblAgeGreaterThan = new javax.swing.JLabel();
        LblAgeLesserTlhan = new javax.swing.JLabel();
        TxtAgeLesserThan = new javax.swing.JTextField();
        CbxAgeOptions = new javax.swing.JComboBox();
        CkbActivateAge = new javax.swing.JCheckBox();
        TxtAgeValue1 = new javax.swing.JTextField();
        BtnSeeResults = new javax.swing.JButton();
        BtnInsParam = new javax.swing.JButton();
        BtnRemoveParam = new javax.swing.JButton();
        ScrlPaneListParams = new javax.swing.JScrollPane();
        ListParams = new javax.swing.JList();
        PanelSetParameters = new javax.swing.JPanel();
        CbxIndustries_FrmUserMain1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        PanelSetParameterOptions = new javax.swing.JPanel();
        PanelDefineParam = new javax.swing.JPanel();
        TxtSearchParamOptions = new javax.swing.JTextField();
        CbxSearchParamsOptions = new javax.swing.JComboBox();
        PanelManualInsParam = new javax.swing.JPanel();
        TxtParamValue = new javax.swing.JTextField();
        LblParamValue = new javax.swing.JLabel();
        PanelUserStats = new javax.swing.JPanel();
        BtnPrev_FrmAdmin = new javax.swing.JButton();
        BtnView_FrmAdmin = new javax.swing.JButton();
        BtnNext_FrmAdmin = new javax.swing.JButton();
        ScrlPaneTbUsers = new javax.swing.JScrollPane();
        TbUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIND MY CAREER");
        setLocationByPlatform(true);
        setResizable(false);

        BtnExit_FrmAdmin.setText("Exit");
        BtnExit_FrmAdmin.setName(""); // NOI18N
        BtnExit_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit_FrmAdminActionPerformed(evt);
            }
        });

        PanelMainCards_FrmAdmin.setPreferredSize(new java.awt.Dimension(595, 410));
        PanelMainCards_FrmAdmin.setLayout(new java.awt.CardLayout());

        CbxOption.setEnabled(false);
        CbxOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxOptionMouseClicked(evt);
            }
        });
        CbxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxOptionActionPerformed(evt);
            }
        });

        LblOptions.setText("Options");

        CbxSections.setMaximumRowCount(5);
        CbxSections.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Industry", "Category", "Jobs", "Skills", "Courses" }));
        CbxSections.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxSectionsItemStateChanged(evt);
            }
        });
        CbxSections.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CbxSectionsFocusGained(evt);
            }
        });
        CbxSections.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxSectionsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbxSectionsMousePressed(evt);
            }
        });
        CbxSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSectionsActionPerformed(evt);
            }
        });

        LblSections.setText("Sections");

        LblOptionName.setText("Name");

        TxtOption.setEditable(false);
        TxtOption.setAutoscrolls(false);

        LblOptionDescr.setText("Description");

        TxtOptionDescr.setEditable(false);
        TxtOptionDescr.setColumns(20);
        TxtOptionDescr.setLineWrap(true);
        TxtOptionDescr.setRows(5);
        ScrlPaneCatDescr_PanelCategory.setViewportView(TxtOptionDescr);

        BtnAction.setText("Action");
        BtnAction.setName(""); // NOI18N
        BtnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActionActionPerformed(evt);
            }
        });

        LblAction.setText("Action");

        CbxAction.setEnabled(false);
        CbxAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxActionMouseClicked(evt);
            }
        });
        CbxAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDbUpdateLayout = new javax.swing.GroupLayout(PanelDbUpdate);
        PanelDbUpdate.setLayout(PanelDbUpdateLayout);
        PanelDbUpdateLayout.setHorizontalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDbUpdateLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrlPaneCatDescr_PanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblOptionDescr)
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDbUpdateLayout.createSequentialGroup()
                                .addComponent(LblSections)
                                .addGap(18, 18, 18)
                                .addComponent(CbxSections, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addComponent(LblOptionName)
                                .addGap(22, 22, 22)
                                .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbxAction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDbUpdateLayout.createSequentialGroup()
                                        .addComponent(LblAction)
                                        .addGap(171, 171, 171))))
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(LblOptions)
                                .addGap(18, 18, 18)
                                .addComponent(CbxOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(76, 76, 76))
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BtnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDbUpdateLayout.setVerticalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxSections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSections)
                    .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblOptions))
                .addGap(46, 46, 46)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblOptionName)
                    .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAction))
                .addGap(35, 35, 35)
                .addComponent(LblOptionDescr)
                .addGap(18, 18, 18)
                .addComponent(ScrlPaneCatDescr_PanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(BtnAction)
                .addGap(22, 22, 22))
        );

        PanelMainCards_FrmAdmin.add(PanelDbUpdate, "PanelDbUpdate");

        PanelUserParameters.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserParameters.setPreferredSize(new java.awt.Dimension(595, 410));

        LblSelectedParams.setText("Selected Fields");

        PanelAge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Age", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TxtAgeGreaterThan.setPreferredSize(new java.awt.Dimension(50, 20));

        LblAgeRange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblAgeRange.setText("<>");
        LblAgeRange.setToolTipText("A range between the first value and the second value");

        TxtAgeValue2.setPreferredSize(new java.awt.Dimension(50, 20));
        TxtAgeValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue2ActionPerformed(evt);
            }
        });

        LblAgeEqualTo.setText("Equal to: ");

        TxtAgeEqualTo.setPreferredSize(new java.awt.Dimension(50, 20));

        LblAgeGreaterThan.setText("Greater than:");

        LblAgeLesserTlhan.setText("Lesser than:");

        TxtAgeLesserThan.setPreferredSize(new java.awt.Dimension(50, 20));

        CbxAgeOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option ", "Equal to", "Greater than", "Lesser than", "Range" }));
        CbxAgeOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxAgeOptionsActionPerformed(evt);
            }
        });

        TxtAgeValue1.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtAgeValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgeLayout = new javax.swing.GroupLayout(PanelAge);
        PanelAge.setLayout(PanelAgeLayout);
        PanelAgeLayout.setHorizontalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addGap(20, 26, Short.MAX_VALUE)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblAgeLesserTlhan)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblAgeGreaterThan)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                .addComponent(LblAgeEqualTo)
                                .addGap(41, 41, 41)
                                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                .addComponent(CkbActivateAge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                        .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblAgeRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        PanelAgeLayout.setVerticalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CkbActivateAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeEqualTo))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeGreaterThan))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeLesserTlhan))
                .addGap(21, 21, 21)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeRange)
                    .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BtnSeeResults.setText("See Results");
        BtnSeeResults.setToolTipText("Set the search parameters for the user's details manually");
        BtnSeeResults.setOpaque(false);

        BtnInsParam.setText("Parameter Set");
        BtnInsParam.setToolTipText("Set the search parameters for the user's details manually");
        BtnInsParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsParamActionPerformed(evt);
            }
        });

        BtnRemoveParam.setText("Remove");
        BtnRemoveParam.setToolTipText("Set the search parameters for the user's details manually");

        ListParams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "First Name", "Second Name", "..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ScrlPaneListParams.setViewportView(ListParams);

        PanelSetParameters.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CbxIndustries_FrmUserMain1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Field", "First Name", "Last Name", "Date of Birth", "Phone", "E-mail" }));
        CbxIndustries_FrmUserMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxIndustries_FrmUserMain1ActionPerformed(evt);
            }
        });

        BtnGroupSetOption.add(jRadioButton1);
        jRadioButton1.setText("Manual Set");

        BtnGroupSetOption.add(jRadioButton2);
        jRadioButton2.setText("Search Set");

        PanelSetParameterOptions.setLayout(new java.awt.CardLayout());

        PanelDefineParam.setMinimumSize(new java.awt.Dimension(173, 121));
        PanelDefineParam.setPreferredSize(new java.awt.Dimension(173, 121));

        TxtSearchParamOptions.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtSearchParamOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchParamOptionsActionPerformed(evt);
            }
        });

        CbxSearchParamsOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search Option", "Begin with", "Contain", "End with" }));
        CbxSearchParamsOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSearchParamsOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDefineParamLayout = new javax.swing.GroupLayout(PanelDefineParam);
        PanelDefineParam.setLayout(PanelDefineParamLayout);
        PanelDefineParamLayout.setHorizontalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CbxSearchParamsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDefineParamLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        PanelDefineParamLayout.setVerticalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CbxSearchParamsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDefineParamLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        PanelSetParameterOptions.add(PanelDefineParam, "card2");

        PanelManualInsParam.setMinimumSize(new java.awt.Dimension(173, 121));

        TxtParamValue.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtParamValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtParamValueActionPerformed(evt);
            }
        });

        LblParamValue.setText("Inset Paramenter Value");

        javax.swing.GroupLayout PanelManualInsParamLayout = new javax.swing.GroupLayout(PanelManualInsParam);
        PanelManualInsParam.setLayout(PanelManualInsParamLayout);
        PanelManualInsParamLayout.setHorizontalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManualInsParamLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblParamValue)
                    .addComponent(TxtParamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelManualInsParamLayout.setVerticalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelManualInsParamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LblParamValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TxtParamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        PanelSetParameterOptions.add(PanelManualInsParam, "card3");

        javax.swing.GroupLayout PanelSetParametersLayout = new javax.swing.GroupLayout(PanelSetParameters);
        PanelSetParameters.setLayout(PanelSetParametersLayout);
        PanelSetParametersLayout.setHorizontalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSetParametersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(CbxIndustries_FrmUserMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSetParametersLayout.setVerticalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CbxIndustries_FrmUserMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(5, 5, 5)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelUserParametersLayout = new javax.swing.GroupLayout(PanelUserParameters);
        PanelUserParameters.setLayout(PanelUserParametersLayout);
        PanelUserParametersLayout.setHorizontalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BtnInsParam)))
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeeResults)
                            .addGroup(PanelUserParametersLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(LblSelectedParams))))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnRemoveParam)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelUserParametersLayout.setVerticalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(LblSelectedParams)
                        .addGap(18, 18, 18)
                        .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRemoveParam))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSeeResults)
                    .addComponent(BtnInsParam))
                .addGap(32, 32, 32))
        );

        PanelMainCards_FrmAdmin.add(PanelUserParameters, "PanelUserParameters");

        PanelUserStats.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserStats.setPreferredSize(new java.awt.Dimension(595, 410));

        BtnPrev_FrmAdmin.setText("Prev.");
        BtnPrev_FrmAdmin.setName(""); // NOI18N

        BtnView_FrmAdmin.setText("View Statistics");
        BtnView_FrmAdmin.setName(""); // NOI18N
        BtnView_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnView_FrmAdminActionPerformed(evt);
            }
        });

        BtnNext_FrmAdmin.setText("Next");
        BtnNext_FrmAdmin.setName(""); // NOI18N

        ScrlPaneTbUsers.setPreferredSize(new java.awt.Dimension(195, 64));

        TbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbUsers.setMinimumSize(new java.awt.Dimension(195, 64));
        TbUsers.setName(""); // NOI18N
        TbUsers.setPreferredSize(new java.awt.Dimension(195, 64));
        ScrlPaneTbUsers.setViewportView(TbUsers);

        javax.swing.GroupLayout PanelUserStatsLayout = new javax.swing.GroupLayout(PanelUserStats);
        PanelUserStats.setLayout(PanelUserStatsLayout);
        PanelUserStatsLayout.setHorizontalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserStatsLayout.createSequentialGroup()
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BtnPrev_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BtnView_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(BtnNext_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        PanelUserStatsLayout.setVerticalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserStatsLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrev_FrmAdmin)
                    .addComponent(BtnView_FrmAdmin)
                    .addComponent(BtnNext_FrmAdmin))
                .addGap(40, 40, 40))
        );

        PanelMainCards_FrmAdmin.add(PanelUserStats, "PanelUserStats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtnExit_FrmAdmin)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    


    //BUTTON EXIT
    //
    private void BtnExit_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit_FrmAdminActionPerformed
        config = new FrmAdminConfig();
        config.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_BtnExit_FrmAdminActionPerformed

    private void CbxSearchParamsOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSearchParamsOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxSearchParamsOptionsActionPerformed

    private void CbxIndustries_FrmUserMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxIndustries_FrmUserMain1ActionPerformed
               
    }//GEN-LAST:event_CbxIndustries_FrmUserMain1ActionPerformed

    private void TxtAgeValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue2ActionPerformed

    private void CbxAgeOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxAgeOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxAgeOptionsActionPerformed

    private void TxtSearchParamOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchParamOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchParamOptionsActionPerformed

    private void BtnInsParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsParamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInsParamActionPerformed

    private void TxtAgeValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue1ActionPerformed

    private void TxtParamValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtParamValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtParamValueActionPerformed

    private void BtnView_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnView_FrmAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnView_FrmAdminActionPerformed

   
    //COMBOBOX AZIONE
    //
    private void CbxActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxActionActionPerformed
        
    }//GEN-LAST:event_CbxActionActionPerformed

    private void BtnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActionActionPerformed
        try {
            String table = this.CbxSections.getSelectedItem().toString();
            this.CbxOption.removeAllItems();
            PreparedStatement a = query.selectAll(table);
            rs = query.execute(a);
//            
            while(rs.next())
            {
                String option = rs.getString(2);
                System.out.println(option);
                this.CbxOption.addItem(option);
            }
            rs.close();
        } catch (SQLException ex) {
            //Logger.getLogger(FrmAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnActionActionPerformed

    //COMBOBOX OPTIONS
    //
    private void CbxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxOptionActionPerformed
        
    }//GEN-LAST:event_CbxOptionActionPerformed

    //COMBOBOX OPTION
    //
    private void CbxOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxOptionMouseClicked
        
    }//GEN-LAST:event_CbxOptionMouseClicked

    private void CbxActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxActionMouseClicked
        //Sets the combobox with the list of the possible actions
        this.CbxAction.removeAllItems();
        this.CbxAction.addItem("Delete");
        this.CbxAction.addItem("Insert");
        this.CbxAction.addItem("Update");
        //According to the action choosen the button caption is changed by consequence
        String text = this.CbxAction.getSelectedItem().toString();
        this.BtnAction.setText(text);
        
    }//GEN-LAST:event_CbxActionMouseClicked

    //CBX SECTIONS
    //
    private void CbxSectionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxSectionsItemStateChanged
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CbxSectionsItemStateChanged

    private void CbxSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSectionsActionPerformed
        // TODO add your han
        //this.CbxOption.setEnabled(true);
    }//GEN-LAST:event_CbxSectionsActionPerformed

    private void CbxSectionsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CbxSectionsFocusGained
        // TODO add your handling code here:
        if (this.CbxSections.getSelectedItem() == null)
        {this.CbxSections.removeItem(null);}
        this.CbxSections.repaint();
        
    }//GEN-LAST:event_CbxSectionsFocusGained

    private void CbxSectionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxSectionsMouseClicked
        // TODO add your handling code here:
        this.CbxOption.setEnabled(true);
    }//GEN-LAST:event_CbxSectionsMouseClicked

    private void CbxSectionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxSectionsMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CbxSectionsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAction;
    private javax.swing.JButton BtnExit_FrmAdmin;
    private javax.swing.ButtonGroup BtnGroupSetOption;
    private javax.swing.JButton BtnInsParam;
    private javax.swing.JButton BtnNext_FrmAdmin;
    private javax.swing.JButton BtnPrev_FrmAdmin;
    private javax.swing.JButton BtnRemoveParam;
    private javax.swing.JButton BtnSeeResults;
    private javax.swing.JButton BtnView_FrmAdmin;
    private javax.swing.JComboBox CbxAction;
    private javax.swing.JComboBox CbxAgeOptions;
    private javax.swing.JComboBox CbxIndustries_FrmUserMain1;
    private javax.swing.JComboBox CbxOption;
    private javax.swing.JComboBox CbxSearchParamsOptions;
    private javax.swing.JComboBox CbxSections;
    private javax.swing.JCheckBox CkbActivateAge;
    private javax.swing.JLabel LblAction;
    private javax.swing.JLabel LblAgeEqualTo;
    private javax.swing.JLabel LblAgeGreaterThan;
    private javax.swing.JLabel LblAgeLesserTlhan;
    private javax.swing.JLabel LblAgeRange;
    private javax.swing.JLabel LblOptionDescr;
    private javax.swing.JLabel LblOptionName;
    private javax.swing.JLabel LblOptions;
    private javax.swing.JLabel LblParamValue;
    private javax.swing.JLabel LblSections;
    private javax.swing.JLabel LblSelectedParams;
    private javax.swing.JList ListParams;
    private javax.swing.JPanel PanelAge;
    private javax.swing.JPanel PanelDbUpdate;
    private javax.swing.JPanel PanelDefineParam;
    private javax.swing.JPanel PanelMainCards_FrmAdmin;
    private javax.swing.JPanel PanelManualInsParam;
    private javax.swing.JPanel PanelSetParameterOptions;
    private javax.swing.JPanel PanelSetParameters;
    private javax.swing.JPanel PanelUserParameters;
    private javax.swing.JPanel PanelUserStats;
    private javax.swing.JScrollPane ScrlPaneCatDescr_PanelCategory;
    private javax.swing.JScrollPane ScrlPaneListParams;
    private javax.swing.JScrollPane ScrlPaneTbUsers;
    private javax.swing.JTable TbUsers;
    private javax.swing.JTextField TxtAgeEqualTo;
    private javax.swing.JTextField TxtAgeGreaterThan;
    private javax.swing.JTextField TxtAgeLesserThan;
    private javax.swing.JTextField TxtAgeValue1;
    private javax.swing.JTextField TxtAgeValue2;
    private javax.swing.JTextField TxtOption;
    private javax.swing.JTextArea TxtOptionDescr;
    private javax.swing.JTextField TxtParamValue;
    private javax.swing.JTextField TxtSearchParamOptions;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
