package Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1100422815
 */
import java.awt.*;
import java.awt.event.*;
import java.awt.font.*;
 
import javax.swing.*;

public class FrmAdmin extends javax.swing.JFrame {

    
    
    /**
     * Creates new form form
     */
    public FrmAdmin() {
        
        initComponents();
        this.setVisible(false);
        this.JDgOptions.setVisible(true);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDgOptions = new javax.swing.JDialog();
        BtnConfigure = new javax.swing.JButton();
        LblJob = new javax.swing.JLabel();
        LblCategory_JDgJob = new javax.swing.JLabel();
        CbxAdminActions = new javax.swing.JComboBox();
        BtnGroupSetOption = new javax.swing.ButtonGroup();
        BtnExit_FrmAdmin = new javax.swing.JButton();
        PanelMainCards_FrmAdmin = new javax.swing.JPanel();
        PanelDbUpdate = new javax.swing.JPanel();
        CbxOption = new javax.swing.JComboBox();
        LblOptions = new javax.swing.JLabel();
        LblSections = new javax.swing.JLabel();
        CbxIndustries_FrmUserMain = new javax.swing.JComboBox();
        LblOptionName = new javax.swing.JLabel();
        TxtOption = new javax.swing.JTextField();
        LblOptionDescr = new javax.swing.JLabel();
        ScrlPaneCatDescr_PanelCategory = new javax.swing.JScrollPane();
        TxtOptionDescr = new javax.swing.JTextArea();
        BtnUpdate_FrmAdmin = new javax.swing.JButton();
        BtnBack_FrmAdmin = new javax.swing.JButton();
        PanelUserParameters = new javax.swing.JPanel();
        LblSelectedParams = new javax.swing.JLabel();
        PanelAge = new javax.swing.JPanel();
        TxtAgeGreaterThan = new javax.swing.JTextField();
        LblAgeRange = new javax.swing.JLabel();
        TxtAgeValue2 = new javax.swing.JTextField();
        LblAgeEqualTo = new javax.swing.JLabel();
        TxtAgeEqualTo = new javax.swing.JTextField();
        LblAgeGreaterThan = new javax.swing.JLabel();
        LblAgeLesserTlhan = new javax.swing.JLabel();
        TxtAgeLesserThan = new javax.swing.JTextField();
        CbxAgeOptions = new javax.swing.JComboBox();
        CkbActivateAge = new javax.swing.JCheckBox();
        TxtAgeValue1 = new javax.swing.JTextField();
        BtnSeeResults = new javax.swing.JButton();
        BtnInsParam = new javax.swing.JButton();
        BtnRemoveParam = new javax.swing.JButton();
        ScrlPaneListParams = new javax.swing.JScrollPane();
        ListParams = new javax.swing.JList();
        PanelSetParameters = new javax.swing.JPanel();
        CbxIndustries_FrmUserMain1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        PanelSetParameterOptions = new javax.swing.JPanel();
        PanelDefineParam = new javax.swing.JPanel();
        TxtSearchParamOptions = new javax.swing.JTextField();
        CbxSearchParamsOptions = new javax.swing.JComboBox();
        PanelManualInsParam = new javax.swing.JPanel();
        TxtParamValue = new javax.swing.JTextField();
        LblParamValue = new javax.swing.JLabel();
        PanelUserStats = new javax.swing.JPanel();
        BtnPrev_FrmAdmin = new javax.swing.JButton();
        BtnView_FrmAdmin = new javax.swing.JButton();
        BtnNext_FrmAdmin = new javax.swing.JButton();
        ScrlPaneTbUsers = new javax.swing.JScrollPane();
        TbUsers = new javax.swing.JTable();

        JDgOptions.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDgOptions.setTitle("CONFIGURE ACTION");
        JDgOptions.setAlwaysOnTop(true);
        JDgOptions.setMinimumSize(new java.awt.Dimension(280, 222));
        JDgOptions.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        JDgOptions.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        JDgOptions.setPreferredSize(new java.awt.Dimension(280, 222));
        JDgOptions.setResizable(false);

        BtnConfigure.setText("Configure");
        BtnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfigureActionPerformed(evt);
            }
        });

        LblJob.setText("ADMINISTRATOR ACTIONS LIST");

        LblCategory_JDgJob.setText("Select Action");

        CbxAdminActions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Update Database", "Search Users Infos" }));
        CbxAdminActions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxAdminActionsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout JDgOptionsLayout = new javax.swing.GroupLayout(JDgOptions.getContentPane());
        JDgOptions.getContentPane().setLayout(JDgOptionsLayout);
        JDgOptionsLayout.setHorizontalGroup(
            JDgOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDgOptionsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JDgOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDgOptionsLayout.createSequentialGroup()
                        .addComponent(LblCategory_JDgJob)
                        .addGap(18, 18, 18)
                        .addComponent(CbxAdminActions, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblJob)
                    .addComponent(BtnConfigure, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        JDgOptionsLayout.setVerticalGroup(
            JDgOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDgOptionsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LblJob)
                .addGap(45, 45, 45)
                .addGroup(JDgOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCategory_JDgJob)
                    .addComponent(CbxAdminActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BtnConfigure)
                .addGap(25, 25, 25))
        );

        JDgOptions.getAccessibleContext().setAccessibleDescription("");
        JDgOptions.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIND MY CAREER");
        setLocationByPlatform(true);
        setResizable(false);

        BtnExit_FrmAdmin.setText("Exit");
        BtnExit_FrmAdmin.setName(""); // NOI18N
        BtnExit_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit_FrmAdminActionPerformed(evt);
            }
        });

        PanelMainCards_FrmAdmin.setPreferredSize(new java.awt.Dimension(595, 410));
        PanelMainCards_FrmAdmin.setLayout(new java.awt.CardLayout());

        CbxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxOptionActionPerformed(evt);
            }
        });

        LblOptions.setText("Options");

        LblSections.setText("Sections");

        CbxIndustries_FrmUserMain.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Industry", "Category", "Courses", "Skills", "Jobs" }));
        CbxIndustries_FrmUserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxIndustries_FrmUserMainActionPerformed(evt);
            }
        });

        LblOptionName.setText("Name");

        TxtOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOptionActionPerformed(evt);
            }
        });

        LblOptionDescr.setText("Description");

        TxtOptionDescr.setColumns(20);
        TxtOptionDescr.setRows(5);
        ScrlPaneCatDescr_PanelCategory.setViewportView(TxtOptionDescr);

        BtnUpdate_FrmAdmin.setText("Update");
        BtnUpdate_FrmAdmin.setMinimumSize(new java.awt.Dimension(70, 23));
        BtnUpdate_FrmAdmin.setPreferredSize(new java.awt.Dimension(70, 23));
        BtnUpdate_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate_FrmAdminActionPerformed(evt);
            }
        });

        BtnBack_FrmAdmin.setText("Back");
        BtnBack_FrmAdmin.setMinimumSize(new java.awt.Dimension(70, 23));
        BtnBack_FrmAdmin.setPreferredSize(new java.awt.Dimension(70, 23));

        javax.swing.GroupLayout PanelDbUpdateLayout = new javax.swing.GroupLayout(PanelDbUpdate);
        PanelDbUpdate.setLayout(PanelDbUpdateLayout);
        PanelDbUpdateLayout.setHorizontalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(BtnUpdate_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBack_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDbUpdateLayout.createSequentialGroup()
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(LblSections)
                        .addGap(22, 22, 22)
                        .addComponent(CbxIndustries_FrmUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(LblOptions)
                        .addGap(18, 18, 18)
                        .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addComponent(LblOptionName)
                                .addGap(22, 22, 22)
                                .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrlPaneCatDescr_PanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblOptionDescr))))
                .addGap(76, 76, 76))
        );
        PanelDbUpdateLayout.setVerticalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxIndustries_FrmUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSections)
                    .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblOptions))
                .addGap(46, 46, 46)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblOptionName)
                    .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(LblOptionDescr)
                .addGap(18, 18, 18)
                .addComponent(ScrlPaneCatDescr_PanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBack_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        PanelMainCards_FrmAdmin.add(PanelDbUpdate, "PanelDbUpdate");

        PanelUserParameters.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserParameters.setPreferredSize(new java.awt.Dimension(595, 410));

        LblSelectedParams.setText("Selected Fields");

        PanelAge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Age", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TxtAgeGreaterThan.setPreferredSize(new java.awt.Dimension(50, 20));

        LblAgeRange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblAgeRange.setText("<>");
        LblAgeRange.setToolTipText("A range between the first value and the second value");

        TxtAgeValue2.setPreferredSize(new java.awt.Dimension(50, 20));
        TxtAgeValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue2ActionPerformed(evt);
            }
        });

        LblAgeEqualTo.setText("Equal to: ");

        TxtAgeEqualTo.setPreferredSize(new java.awt.Dimension(50, 20));

        LblAgeGreaterThan.setText("Greater than:");

        LblAgeLesserTlhan.setText("Lesser than:");

        TxtAgeLesserThan.setPreferredSize(new java.awt.Dimension(50, 20));

        CbxAgeOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option ", "Equal to", "Greater than", "Lesser than", "Range" }));
        CbxAgeOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxAgeOptionsActionPerformed(evt);
            }
        });

        TxtAgeValue1.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtAgeValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgeLayout = new javax.swing.GroupLayout(PanelAge);
        PanelAge.setLayout(PanelAgeLayout);
        PanelAgeLayout.setHorizontalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addGap(20, 26, Short.MAX_VALUE)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblAgeLesserTlhan)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblAgeGreaterThan)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                .addComponent(LblAgeEqualTo)
                                .addGap(41, 41, 41)
                                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                .addComponent(CkbActivateAge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                        .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblAgeRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        PanelAgeLayout.setVerticalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CkbActivateAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeEqualTo))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeGreaterThan))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeLesserTlhan))
                .addGap(21, 21, 21)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeRange)
                    .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BtnSeeResults.setText("See Results");
        BtnSeeResults.setToolTipText("Set the search parameters for the user's details manually");

        BtnInsParam.setText("Parameter Set");
        BtnInsParam.setToolTipText("Set the search parameters for the user's details manually");
        BtnInsParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsParamActionPerformed(evt);
            }
        });

        BtnRemoveParam.setText("Remove");
        BtnRemoveParam.setToolTipText("Set the search parameters for the user's details manually");

        ListParams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "First Name", "Second Name", "..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ScrlPaneListParams.setViewportView(ListParams);

        PanelSetParameters.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CbxIndustries_FrmUserMain1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Field", "First Name", "Last Name", "Date of Birth", "Phone", "E-mail" }));
        CbxIndustries_FrmUserMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxIndustries_FrmUserMain1ActionPerformed(evt);
            }
        });

        BtnGroupSetOption.add(jRadioButton1);
        jRadioButton1.setText("Manual Set");

        BtnGroupSetOption.add(jRadioButton2);
        jRadioButton2.setText("Search Set");

        PanelSetParameterOptions.setLayout(new java.awt.CardLayout());

        PanelDefineParam.setMinimumSize(new java.awt.Dimension(173, 121));
        PanelDefineParam.setPreferredSize(new java.awt.Dimension(173, 121));

        TxtSearchParamOptions.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtSearchParamOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchParamOptionsActionPerformed(evt);
            }
        });

        CbxSearchParamsOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search Option", "Begin with", "Contain", "End with" }));
        CbxSearchParamsOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSearchParamsOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDefineParamLayout = new javax.swing.GroupLayout(PanelDefineParam);
        PanelDefineParam.setLayout(PanelDefineParamLayout);
        PanelDefineParamLayout.setHorizontalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CbxSearchParamsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDefineParamLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        PanelDefineParamLayout.setVerticalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CbxSearchParamsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDefineParamLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        PanelSetParameterOptions.add(PanelDefineParam, "card2");

        PanelManualInsParam.setMinimumSize(new java.awt.Dimension(173, 121));

        TxtParamValue.setPreferredSize(new java.awt.Dimension(59, 20));
        TxtParamValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtParamValueActionPerformed(evt);
            }
        });

        LblParamValue.setText("Inset Paramenter Value");

        javax.swing.GroupLayout PanelManualInsParamLayout = new javax.swing.GroupLayout(PanelManualInsParam);
        PanelManualInsParam.setLayout(PanelManualInsParamLayout);
        PanelManualInsParamLayout.setHorizontalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManualInsParamLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblParamValue)
                    .addComponent(TxtParamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelManualInsParamLayout.setVerticalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelManualInsParamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LblParamValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TxtParamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        PanelSetParameterOptions.add(PanelManualInsParam, "card3");

        javax.swing.GroupLayout PanelSetParametersLayout = new javax.swing.GroupLayout(PanelSetParameters);
        PanelSetParameters.setLayout(PanelSetParametersLayout);
        PanelSetParametersLayout.setHorizontalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSetParametersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(CbxIndustries_FrmUserMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSetParametersLayout.setVerticalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CbxIndustries_FrmUserMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(5, 5, 5)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelUserParametersLayout = new javax.swing.GroupLayout(PanelUserParameters);
        PanelUserParameters.setLayout(PanelUserParametersLayout);
        PanelUserParametersLayout.setHorizontalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BtnInsParam)))
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeeResults)
                            .addGroup(PanelUserParametersLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(LblSelectedParams))))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnRemoveParam)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelUserParametersLayout.setVerticalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(LblSelectedParams)
                        .addGap(18, 18, 18)
                        .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRemoveParam))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSeeResults)
                    .addComponent(BtnInsParam))
                .addGap(32, 32, 32))
        );

        PanelMainCards_FrmAdmin.add(PanelUserParameters, "PanelUserParameters");

        PanelUserStats.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserStats.setPreferredSize(new java.awt.Dimension(595, 410));

        BtnPrev_FrmAdmin.setText("Prev.");
        BtnPrev_FrmAdmin.setName(""); // NOI18N

        BtnView_FrmAdmin.setText("View Statistics");
        BtnView_FrmAdmin.setName(""); // NOI18N
        BtnView_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnView_FrmAdminActionPerformed(evt);
            }
        });

        BtnNext_FrmAdmin.setText("Next");
        BtnNext_FrmAdmin.setName(""); // NOI18N

        ScrlPaneTbUsers.setPreferredSize(new java.awt.Dimension(195, 64));

        TbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbUsers.setMinimumSize(new java.awt.Dimension(195, 64));
        TbUsers.setName(""); // NOI18N
        TbUsers.setPreferredSize(new java.awt.Dimension(195, 64));
        ScrlPaneTbUsers.setViewportView(TbUsers);

        javax.swing.GroupLayout PanelUserStatsLayout = new javax.swing.GroupLayout(PanelUserStats);
        PanelUserStats.setLayout(PanelUserStatsLayout);
        PanelUserStatsLayout.setHorizontalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserStatsLayout.createSequentialGroup()
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BtnPrev_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BtnView_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(BtnNext_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        PanelUserStatsLayout.setVerticalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserStatsLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrev_FrmAdmin)
                    .addComponent(BtnView_FrmAdmin)
                    .addComponent(BtnNext_FrmAdmin))
                .addGap(40, 40, 40))
        );

        PanelMainCards_FrmAdmin.add(PanelUserStats, "PanelUserStats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(BtnExit_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(BtnExit_FrmAdmin)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExit_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit_FrmAdminActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnExit_FrmAdminActionPerformed

    private void BtnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfigureActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.JDgOptions.dispose();
    }//GEN-LAST:event_BtnConfigureActionPerformed

    private void CbxIndustries_FrmUserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxIndustries_FrmUserMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxIndustries_FrmUserMainActionPerformed

    private void CbxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxOptionActionPerformed

    private void BtnUpdate_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate_FrmAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate_FrmAdminActionPerformed

    private void CbxSearchParamsOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSearchParamsOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxSearchParamsOptionsActionPerformed

    private void CbxIndustries_FrmUserMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxIndustries_FrmUserMain1ActionPerformed
               
    }//GEN-LAST:event_CbxIndustries_FrmUserMain1ActionPerformed

    private void TxtAgeValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue2ActionPerformed

    private void CbxAgeOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxAgeOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxAgeOptionsActionPerformed

    private void TxtSearchParamOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchParamOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchParamOptionsActionPerformed

    private void BtnInsParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsParamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInsParamActionPerformed

    private void TxtAgeValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue1ActionPerformed

    private void TxtParamValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtParamValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtParamValueActionPerformed

    private void BtnView_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnView_FrmAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnView_FrmAdminActionPerformed

    private void CbxAdminActionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxAdminActionsItemStateChanged
            
    }//GEN-LAST:event_CbxAdminActionsItemStateChanged

    private void TxtOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack_FrmAdmin;
    private javax.swing.JButton BtnConfigure;
    private javax.swing.JButton BtnExit_FrmAdmin;
    private javax.swing.ButtonGroup BtnGroupSetOption;
    private javax.swing.JButton BtnInsParam;
    private javax.swing.JButton BtnNext_FrmAdmin;
    private javax.swing.JButton BtnPrev_FrmAdmin;
    private javax.swing.JButton BtnRemoveParam;
    private javax.swing.JButton BtnSeeResults;
    private javax.swing.JButton BtnUpdate_FrmAdmin;
    private javax.swing.JButton BtnView_FrmAdmin;
    private javax.swing.JComboBox CbxAdminActions;
    private javax.swing.JComboBox CbxAgeOptions;
    private javax.swing.JComboBox CbxIndustries_FrmUserMain;
    private javax.swing.JComboBox CbxIndustries_FrmUserMain1;
    private javax.swing.JComboBox CbxOption;
    private javax.swing.JComboBox CbxSearchParamsOptions;
    private javax.swing.JCheckBox CkbActivateAge;
    private javax.swing.JDialog JDgOptions;
    private javax.swing.JLabel LblAgeEqualTo;
    private javax.swing.JLabel LblAgeGreaterThan;
    private javax.swing.JLabel LblAgeLesserTlhan;
    private javax.swing.JLabel LblAgeRange;
    private javax.swing.JLabel LblCategory_JDgJob;
    private javax.swing.JLabel LblJob;
    private javax.swing.JLabel LblOptionDescr;
    private javax.swing.JLabel LblOptionName;
    private javax.swing.JLabel LblOptions;
    private javax.swing.JLabel LblParamValue;
    private javax.swing.JLabel LblSections;
    private javax.swing.JLabel LblSelectedParams;
    private javax.swing.JList ListParams;
    private javax.swing.JPanel PanelAge;
    private javax.swing.JPanel PanelDbUpdate;
    private javax.swing.JPanel PanelDefineParam;
    private javax.swing.JPanel PanelMainCards_FrmAdmin;
    private javax.swing.JPanel PanelManualInsParam;
    private javax.swing.JPanel PanelSetParameterOptions;
    private javax.swing.JPanel PanelSetParameters;
    private javax.swing.JPanel PanelUserParameters;
    private javax.swing.JPanel PanelUserStats;
    private javax.swing.JScrollPane ScrlPaneCatDescr_PanelCategory;
    private javax.swing.JScrollPane ScrlPaneListParams;
    private javax.swing.JScrollPane ScrlPaneTbUsers;
    private javax.swing.JTable TbUsers;
    private javax.swing.JTextField TxtAgeEqualTo;
    private javax.swing.JTextField TxtAgeGreaterThan;
    private javax.swing.JTextField TxtAgeLesserThan;
    private javax.swing.JTextField TxtAgeValue1;
    private javax.swing.JTextField TxtAgeValue2;
    private javax.swing.JTextField TxtOption;
    private javax.swing.JTextArea TxtOptionDescr;
    private javax.swing.JTextField TxtParamValue;
    private javax.swing.JTextField TxtSearchParamOptions;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
