/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.*;

/**
 *
 * @author Donati
 */
public class FrmAdminConfig extends javax.swing.JFrame {

    FrmAdmin admin = new FrmAdmin();
   // CardLayout card = new CardLayout();
    /**
     * Creates new form FrmAdminConfig
     */
    public FrmAdminConfig() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExitApp_FrmAdmin = new javax.swing.JButton();
        BtnConfigure = new javax.swing.JButton();
        LblDescrJDgOptions = new javax.swing.JLabel();
        LblTask = new javax.swing.JLabel();
        CbxTask = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN SCREEN");
        setMaximumSize(new java.awt.Dimension(335, 310));
        setMinimumSize(new java.awt.Dimension(335, 285));
        setPreferredSize(new java.awt.Dimension(335, 310));

        BtnExitApp_FrmAdmin.setText("Close App");
        BtnExitApp_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitApp_FrmAdminActionPerformed(evt);
            }
        });

        BtnConfigure.setText("Configure");
        BtnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfigureActionPerformed(evt);
            }
        });

        LblDescrJDgOptions.setText("<html>CHOOSE A TASK TO PERFORM <br><br> Please, choose one task from the list below and <br> then click on Configure to proceed.</html>");
        LblDescrJDgOptions.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LblDescrJDgOptions.setMaximumSize(new java.awt.Dimension(270, 200));
        LblDescrJDgOptions.setMinimumSize(new java.awt.Dimension(270, 70));
        LblDescrJDgOptions.setPreferredSize(new java.awt.Dimension(270, 70));

        LblTask.setText("Select a Task");

        CbxTask.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Edit Profile", "Modify Database", "Search by Personal Infos", "Other Parameters" }));
        CbxTask.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxTaskItemStateChanged(evt);
            }
        });
        CbxTask.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                CbxTaskPopupMenuWillBecomeVisible(evt);
            }
        });
        CbxTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxTaskMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbxTaskMousePressed(evt);
            }
        });
        CbxTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtnConfigure, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(BtnExitApp_FrmAdmin)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDescrJDgOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTask)
                        .addGap(18, 18, 18)
                        .addComponent(CbxTask, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LblDescrJDgOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTask)
                    .addComponent(CbxTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfigure)
                    .addComponent(BtnExitApp_FrmAdmin))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitApp_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitApp_FrmAdminActionPerformed
        //String message = "Are you sure you want to quit the program?";
        //        int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Save your Previous Note First?","Warning",dialogButton);
        //if(dialogResult == JOptionPane.YES_OPTION){
            //            msgbox.setMessage(message);
            //            msgbox.setTitle("Class Not Found");
            //            msgbox.setMsgBoxType("Warning");
            //            String exit = msgbox.confMsgBox();
            //            if(exit == "yes")
            //            {
                //Exit from the program
                System.exit(0);
                //}
    }//GEN-LAST:event_BtnExitApp_FrmAdminActionPerformed

    private void BtnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfigureActionPerformed
        String txt = this.CbxTask.getSelectedItem().toString();
       // this.dispose();
         
       
            if(txt == "Edit Profile")
            {    
            FrmEditProfile edit = new FrmEditProfile();
            edit.setVisible(true);
            
            }
            else 
            {
                admin.setVisible(true);
         
        admin.pane(txt);
            }
            this.dispose();
        
        

    }//GEN-LAST:event_BtnConfigureActionPerformed

    private void CbxTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTaskActionPerformed
        String txt = this.CbxTask.getSelectedItem().toString();
        String text = null;
        switch(txt)
        {
            case "Edit Profile":
                text = "<html>"
                     + "ACCESS PERSONAL PROFILE <br><br> "
                     + "Redirect the user to their profile <br> "
                     + "to view or edit their personal details."
                     + "</html>";
                        
                break;
        
            case "Modiry Database": 
                text = "<html>"
                     + "MODIFY DATABASE INFORMATIONS <br><br> "
                     + "Redirect to the modify database page where "
                     + "is possible to view, insert, update or delete data"
                     + " from the database."
                     + "</html>";
                break;
            case "Search by Personal Infos":
                text = "<html>"
                     + "SEARCH USERS BY PERSONAL DETAILS <br><br> "
                     + "Redirect to the user page where is possible to interrogate "
                     + "the database to retrieve a list of users filtering them  "
                     + "by their personal details."
                     + "</html>";
                break;
            case "Other Parameters":
                text = "<html>"
                     + "OTHER PARAMETERS <br><br> "
                     + "This section is dedicated to interrogate the "
                     + "database retrieving the users, eg, by industry, by study area, by career etc."
                     + "</html>";
                break;
            default:
                text = "<html>"
                     + "CHOOSE A TASK TO PERFORM <br><br> "
                     + "Please, choose one task from the list below and  "
                     + "then click on Configure to proceed."
                     + "</html>";
                break;
        }
        this.LblDescrJDgOptions.setText(text);
    }//GEN-LAST:event_CbxTaskActionPerformed

    private void CbxTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxTaskMouseClicked
       
       //this.CbxTask.hidePopup();
    }//GEN-LAST:event_CbxTaskMouseClicked

    private void CbxTaskItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxTaskItemStateChanged
        
    }//GEN-LAST:event_CbxTaskItemStateChanged

    private void CbxTaskPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbxTaskPopupMenuWillBecomeVisible
        
    }//GEN-LAST:event_CbxTaskPopupMenuWillBecomeVisible

    private void CbxTaskMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxTaskMousePressed
         
    }//GEN-LAST:event_CbxTaskMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfigure;
    private javax.swing.JButton BtnExitApp_FrmAdmin;
    private javax.swing.JComboBox CbxTask;
    private javax.swing.JLabel LblDescrJDgOptions;
    private javax.swing.JLabel LblTask;
    // End of variables declaration//GEN-END:variables
}
