/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.*;

/**
 *
 * @author Donati
 */
public class FrmAdminConfig extends javax.swing.JFrame {

    FrmAdmin admin = new FrmAdmin();
    CardLayout card = new CardLayout();
    /**
     * Creates new form FrmAdminConfig
     */
    public FrmAdminConfig() {
        initComponents();
        //Sets the combobox for the task for the admin
        this.CbxTask.removeAllItems();
        this.CbxTask.addItem("Edit Profile");
        this.CbxTask.addItem("Update Database");
        this.CbxTask.addItem("Search Users Infos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExitApp_FrmAdmin = new javax.swing.JButton();
        BtnConfigure = new javax.swing.JButton();
        LblDescrJDgOptions = new javax.swing.JLabel();
        LblTask = new javax.swing.JLabel();
        CbxTask = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN SCREEN");
        setMinimumSize(new java.awt.Dimension(335, 285));
        setPreferredSize(new java.awt.Dimension(335, 285));
        setResizable(false);

        BtnExitApp_FrmAdmin.setText("Close App");
        BtnExitApp_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitApp_FrmAdminActionPerformed(evt);
            }
        });

        BtnConfigure.setText("Configure");
        BtnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfigureActionPerformed(evt);
            }
        });

        LblDescrJDgOptions.setText("<html>CHOOSE A TASK TO PERFORM <br><br> Please, choose one task from the list below and <br> then click on Configure to proceed.</html>");

        LblTask.setText("Select Action");

        CbxTask.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Update Database", "Search Users Infos", "Edit Profile", " ", " " }));
        CbxTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTask)
                        .addGap(18, 18, 18)
                        .addComponent(CbxTask, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblDescrJDgOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnConfigure, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExitApp_FrmAdmin)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LblDescrJDgOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTask)
                    .addComponent(CbxTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfigure)
                    .addComponent(BtnExitApp_FrmAdmin))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitApp_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitApp_FrmAdminActionPerformed
        //String message = "Are you sure you want to quit the program?";
        //        int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Save your Previous Note First?","Warning",dialogButton);
        //if(dialogResult == JOptionPane.YES_OPTION){
            //            msgbox.setMessage(message);
            //            msgbox.setTitle("Class Not Found");
            //            msgbox.setMsgBoxType("Warning");
            //            String exit = msgbox.confMsgBox();
            //            if(exit == "yes")
            //            {
                //Exit from the program
                System.exit(0);
                //}
    }//GEN-LAST:event_BtnExitApp_FrmAdminActionPerformed

    private void BtnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfigureActionPerformed
        String txt = this.CbxTask.getSelectedItem().toString();
        admin.pane(txt);
        
            if(txt == "Edit Profile")
            {    
            FrmEditProfile edit = new FrmEditProfile();
            edit.setVisible(true);
            
            }
            this.dispose();
        
        

    }//GEN-LAST:event_BtnConfigureActionPerformed

    private void CbxTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTaskActionPerformed
        
    }//GEN-LAST:event_CbxTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfigure;
    private javax.swing.JButton BtnExitApp_FrmAdmin;
    private javax.swing.JComboBox CbxTask;
    private javax.swing.JLabel LblDescrJDgOptions;
    private javax.swing.JLabel LblTask;
    // End of variables declaration//GEN-END:variables
}
