package Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1100422815
 */
//import java.awt.*;
import java.awt.CardLayout;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

 
public class FrmAdmin extends javax.swing.JFrame {

    //Create an instance of the class Queries
    //Queries query;
    //New instance of CardLayout
    CardLayout card = new CardLayout();
    PopUpMsgBox msgbox = new PopUpMsgBox();
    QueriesStefano query = new QueriesStefano();
    ResultSet rs;
    //Define a var DefaultListModel to can add/remove items from the list for the user param panel
    DefaultListModel listModel = new DefaultListModel();
    FrmAdminConfig config;
    String descr = null;
    String[][] params = null;
    
    int capacity =0;
       Map<String, String> section = new HashMap<String, String>(capacity, 1);
        //Here i declare two arraylists where i'm gonna import the maps and then use for the calculations
        List<HashMap<String, String>> sectionList = new ArrayList<HashMap<String, String>>();
    
    /**
     * Creates new form form
     */
    public FrmAdmin() {
        
        initComponents();
        //CONNECTION PARAMETERS SETTINGS
        //db = new Database();
        query.setUser("root");
        query.setPassword("");
        query.setHost("localhost");
        query.setPort("3306");
        query.setDatabase("findmycareer");
        this.ScrlBarOption.setVisible(false);
        
        int totComp = this.PanelAge.getComponentCount();
        for(int i=0; i<totComp; i++)
        {
            this.PanelAge.getComponent(i).setEnabled(false);
        }    
        this.CkbAge.setEnabled(true);
        this.RBtnDefine.setSelected(true);
    //SET THE OPTION DIALOG BOX
        //
        //Sets the JFrame invisible so the JDialogbox can appear without having the form visible underneath
        
        
        this.setVisible(false);
        
                
    }

    public void pane(String pane)
    {
        
        switch(pane)
        {
            case "Update Database":
            card = (CardLayout)this.PanelMainCards_FrmAdmin.getLayout();
            card.show(this.PanelMainCards_FrmAdmin, "PanelDbUpdate");
            
            break;
            case "Search Users Infos":
            card = (CardLayout)this.PanelMainCards_FrmAdmin.getLayout();
            card.show(this.PanelMainCards_FrmAdmin, "PanelUserParameters");
            int width = this.PanelUserParameters.getSize().width;
            this.setSize(630, this.getSize().height);
            break;
        }
        this.setVisible(true);
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupSetOption = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        BtnExit_FrmAdmin = new javax.swing.JButton();
        PanelMainCards_FrmAdmin = new javax.swing.JPanel();
        PanelUserParameters = new javax.swing.JPanel();
        LblSelectedParams = new javax.swing.JLabel();
        PanelAge = new javax.swing.JPanel();
        TxtAgeGreaterThan = new javax.swing.JTextField();
        LblAgeRange = new javax.swing.JLabel();
        TxtAgeValue2 = new javax.swing.JTextField();
        LblAgeEqualTo = new javax.swing.JLabel();
        TxtAgeEqualTo = new javax.swing.JTextField();
        LblAgeGreaterThan = new javax.swing.JLabel();
        LblAgeLesserThan = new javax.swing.JLabel();
        TxtAgeLesserThan = new javax.swing.JTextField();
        CbxAgeOptions = new javax.swing.JComboBox();
        TxtAgeValue1 = new javax.swing.JTextField();
        CkbAge = new javax.swing.JCheckBox();
        BtnSeeResults = new javax.swing.JButton();
        BtnInsParam = new javax.swing.JButton();
        BtnRemoveParam = new javax.swing.JButton();
        ScrlPaneListParams = new javax.swing.JScrollPane();
        ListParams = new javax.swing.JList();
        PanelSetParameters = new javax.swing.JPanel();
        CbxFields = new javax.swing.JComboBox();
        RBtnManual = new javax.swing.JRadioButton();
        RBtnDefine = new javax.swing.JRadioButton();
        PanelSetParameterOptions = new javax.swing.JPanel();
        PanelDefineParam = new javax.swing.JPanel();
        TxtSearchParamOptions = new javax.swing.JTextField();
        CbxSearchParamsOptions = new javax.swing.JComboBox();
        ScrlBarSearch = new javax.swing.JScrollBar();
        PanelManualInsParam = new javax.swing.JPanel();
        LblParamValue = new javax.swing.JLabel();
        TxtParamValue = new javax.swing.JTextField();
        ScrlBarManual = new javax.swing.JScrollBar();
        PanelDbUpdate = new javax.swing.JPanel();
        CbxOption = new javax.swing.JComboBox();
        CbxSections = new javax.swing.JComboBox();
        LblOptions = new javax.swing.JLabel();
        LblSections = new javax.swing.JLabel();
        LblOptionName = new javax.swing.JLabel();
        LblOptionDescr = new javax.swing.JLabel();
        ScrlPaneOptionDescr = new javax.swing.JScrollPane();
        TxtOptionDescr = new javax.swing.JTextArea();
        LblAction = new javax.swing.JLabel();
        CbxAction = new javax.swing.JComboBox();
        TxtOption = new javax.swing.JTextField();
        ScrlBarOption = new javax.swing.JScrollBar();
        BtnAction = new javax.swing.JButton();
        PanelUserStats = new javax.swing.JPanel();
        BtnPrev_FrmAdmin = new javax.swing.JButton();
        BtnView_FrmAdmin = new javax.swing.JButton();
        BtnNext_FrmAdmin = new javax.swing.JButton();
        ScrlPaneTbUsers = new javax.swing.JScrollPane();
        TbUsers = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIND MY CAREER");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(595, 485));
        setResizable(false);

        BtnExit_FrmAdmin.setText("Exit");
        BtnExit_FrmAdmin.setName(""); // NOI18N
        BtnExit_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit_FrmAdminActionPerformed(evt);
            }
        });

        PanelMainCards_FrmAdmin.setPreferredSize(new java.awt.Dimension(595, 410));
        PanelMainCards_FrmAdmin.setLayout(new java.awt.CardLayout());

        PanelUserParameters.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserParameters.setPreferredSize(new java.awt.Dimension(595, 410));

        LblSelectedParams.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSelectedParams.setText("Selected Fields");

        PanelAge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Age", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TxtAgeGreaterThan.setPreferredSize(new java.awt.Dimension(50, 25));
        TxtAgeGreaterThan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAgeGreaterThanKeyReleased(evt);
            }
        });

        LblAgeRange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblAgeRange.setText("<>");
        LblAgeRange.setToolTipText("A range between the first value and the second value");

        TxtAgeValue2.setPreferredSize(new java.awt.Dimension(50, 25));
        TxtAgeValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue2ActionPerformed(evt);
            }
        });
        TxtAgeValue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAgeValue2KeyReleased(evt);
            }
        });

        LblAgeEqualTo.setText("Equal to: ");

        TxtAgeEqualTo.setPreferredSize(new java.awt.Dimension(50, 25));
        TxtAgeEqualTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAgeEqualToKeyReleased(evt);
            }
        });

        LblAgeGreaterThan.setText("Greater than:");

        LblAgeLesserThan.setText("Lesser than:");

        TxtAgeLesserThan.setPreferredSize(new java.awt.Dimension(50, 25));
        TxtAgeLesserThan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAgeLesserThanKeyReleased(evt);
            }
        });

        CbxAgeOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equal to", "Greater than", "Lesser than", "Range" }));
        CbxAgeOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxAgeOptionsActionPerformed(evt);
            }
        });

        TxtAgeValue1.setPreferredSize(new java.awt.Dimension(50, 25));
        TxtAgeValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeValue1ActionPerformed(evt);
            }
        });
        TxtAgeValue1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAgeValue1KeyReleased(evt);
            }
        });

        CkbAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkbAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgeLayout = new javax.swing.GroupLayout(PanelAge);
        PanelAge.setLayout(PanelAgeLayout);
        PanelAgeLayout.setHorizontalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addGap(20, 26, Short.MAX_VALUE)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAgeLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LblAgeGreaterThan)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                    .addComponent(LblAgeEqualTo)
                                    .addGap(41, 41, 41)
                                    .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                                    .addComponent(CkbAge)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                            .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(LblAgeRange)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgeLayout.createSequentialGroup()
                        .addComponent(LblAgeLesserThan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        PanelAgeLayout.setVerticalGroup(
            PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbxAgeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CkbAge))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeEqualTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeEqualTo))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeGreaterThan))
                .addGap(18, 18, 18)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeLesserThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeLesserThan))
                .addGap(21, 21, 21)
                .addGroup(PanelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAgeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgeRange)
                    .addComponent(TxtAgeValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        BtnSeeResults.setText("See Results");
        BtnSeeResults.setToolTipText("Set the search parameters for the user's details manually");
        BtnSeeResults.setEnabled(false);
        BtnSeeResults.setOpaque(false);
        BtnSeeResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeeResultsActionPerformed(evt);
            }
        });

        BtnInsParam.setText("Parameter Set");
        BtnInsParam.setToolTipText("Set the search parameters for the user's details manually");
        BtnInsParam.setEnabled(false);
        BtnInsParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsParamActionPerformed(evt);
            }
        });

        BtnRemoveParam.setText("Remove");
        BtnRemoveParam.setToolTipText("Set the search parameters for the user's details manually");
        BtnRemoveParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveParamActionPerformed(evt);
            }
        });

        ListParams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "First Name", "Second Name", "..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ScrlPaneListParams.setViewportView(ListParams);

        PanelSetParameters.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CbxFields.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Name", "Last Name", "Date of Birth", "Phone", "E-mail" }));
        CbxFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxFieldsActionPerformed(evt);
            }
        });

        BtnGroupSetOption.add(RBtnManual);
        RBtnManual.setText("Manual Set");
        RBtnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnManualActionPerformed(evt);
            }
        });

        BtnGroupSetOption.add(RBtnDefine);
        RBtnDefine.setText("Search Set");
        RBtnDefine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnDefineActionPerformed(evt);
            }
        });

        PanelSetParameterOptions.setLayout(new java.awt.CardLayout());

        PanelDefineParam.setMinimumSize(new java.awt.Dimension(173, 121));
        PanelDefineParam.setPreferredSize(new java.awt.Dimension(173, 121));

        TxtSearchParamOptions.setEnabled(false);
        TxtSearchParamOptions.setMinimumSize(new java.awt.Dimension(117, 25));
        TxtSearchParamOptions.setPreferredSize(new java.awt.Dimension(117, 25));
        TxtSearchParamOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchParamOptionsActionPerformed(evt);
            }
        });
        TxtSearchParamOptions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSearchParamOptionsKeyReleased(evt);
            }
        });

        CbxSearchParamsOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search Option", "Begin with", "Contain", "End with" }));
        CbxSearchParamsOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSearchParamsOptionsActionPerformed(evt);
            }
        });

        ScrlBarSearch.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        ScrlBarSearch.setModel(TxtSearchParamOptions.getHorizontalVisibility());

        javax.swing.GroupLayout PanelDefineParamLayout = new javax.swing.GroupLayout(PanelDefineParam);
        PanelDefineParam.setLayout(PanelDefineParamLayout);
        PanelDefineParamLayout.setHorizontalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CbxSearchParamsOptions, 0, 120, Short.MAX_VALUE)
                    .addComponent(ScrlBarSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelDefineParamLayout.setVerticalGroup(
            PanelDefineParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefineParamLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CbxSearchParamsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtSearchParamOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrlBarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        PanelSetParameterOptions.add(PanelDefineParam, "PanelDefineParam");

        PanelManualInsParam.setMinimumSize(new java.awt.Dimension(173, 121));

        LblParamValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblParamValue.setText("Inset Value");

        TxtParamValue.setMinimumSize(new java.awt.Dimension(6, 25));
        TxtParamValue.setPreferredSize(new java.awt.Dimension(117, 25));
        TxtParamValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtParamValueKeyReleased(evt);
            }
        });

        ScrlBarManual.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        ScrlBarManual.setModel(TxtParamValue.getHorizontalVisibility());

        javax.swing.GroupLayout PanelManualInsParamLayout = new javax.swing.GroupLayout(PanelManualInsParam);
        PanelManualInsParam.setLayout(PanelManualInsParamLayout);
        PanelManualInsParamLayout.setHorizontalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManualInsParamLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LblParamValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtParamValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrlBarManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelManualInsParamLayout.setVerticalGroup(
            PanelManualInsParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelManualInsParamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LblParamValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtParamValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrlBarManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PanelSetParameterOptions.add(PanelManualInsParam, "PanelManualParam");

        javax.swing.GroupLayout PanelSetParametersLayout = new javax.swing.GroupLayout(PanelSetParameters);
        PanelSetParameters.setLayout(PanelSetParametersLayout);
        PanelSetParametersLayout.setHorizontalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSetParametersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBtnManual)
                    .addComponent(RBtnDefine)
                    .addComponent(CbxFields, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSetParametersLayout.setVerticalGroup(
            PanelSetParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSetParametersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CbxFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RBtnManual)
                .addGap(5, 5, 5)
                .addComponent(RBtnDefine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSetParameterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelUserParametersLayout = new javax.swing.GroupLayout(PanelUserParameters);
        PanelUserParameters.setLayout(PanelUserParametersLayout);
        PanelUserParametersLayout.setHorizontalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(BtnInsParam))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSeeResults)
                            .addComponent(BtnRemoveParam)))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(LblSelectedParams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelUserParametersLayout.setVerticalGroup(
            PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserParametersLayout.createSequentialGroup()
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(LblSelectedParams)
                        .addGap(18, 18, 18)
                        .addComponent(ScrlPaneListParams, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRemoveParam))
                    .addGroup(PanelUserParametersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelSetParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(PanelUserParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSeeResults)
                    .addComponent(BtnInsParam))
                .addGap(32, 32, 32))
        );

        PanelMainCards_FrmAdmin.add(PanelUserParameters, "PanelUserParameters");

        PanelDbUpdate.setMaximumSize(new java.awt.Dimension(595, 410));
        PanelDbUpdate.setMinimumSize(new java.awt.Dimension(595, 410));

        CbxOption.setAutoscrolls(true);
        CbxOption.setEnabled(false);
        CbxOption.setMaximumSize(new java.awt.Dimension(169, 20));
        CbxOption.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                CbxOptionPopupMenuWillBecomeVisible(evt);
            }
        });
        CbxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxOptionActionPerformed(evt);
            }
        });

        CbxSections.setMaximumRowCount(6);
        CbxSections.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Category", "Courses", "Industry", "Jobs", "Skills" }));
        CbxSections.setMaximumSize(new java.awt.Dimension(130, 20));
        CbxSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSectionsActionPerformed(evt);
            }
        });

        LblOptions.setText("Options");

        LblSections.setText("Sections");

        LblOptionName.setText("Name");

        LblOptionDescr.setText("Description");

        TxtOptionDescr.setEditable(false);
        TxtOptionDescr.setColumns(20);
        TxtOptionDescr.setLineWrap(true);
        TxtOptionDescr.setRows(5);
        TxtOptionDescr.setWrapStyleWord(true);
        ScrlPaneOptionDescr.setViewportView(TxtOptionDescr);

        LblAction.setText("Action");

        CbxAction.setEnabled(false);
        CbxAction.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CbxActionPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CbxAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxActionMouseClicked(evt);
            }
        });
        CbxAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxActionActionPerformed(evt);
            }
        });

        TxtOption.setEditable(false);
        TxtOption.setMaximumSize(new java.awt.Dimension(143, 23));
        TxtOption.setMinimumSize(new java.awt.Dimension(143, 23));
        TxtOption.setPreferredSize(new java.awt.Dimension(143, 23));
        TxtOption.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TxtOptionPropertyChange(evt);
            }
        });
        TxtOption.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtOptionKeyReleased(evt);
            }
        });

        ScrlBarOption.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        ScrlBarOption.setModel(TxtOption.getHorizontalVisibility());

        BtnAction.setText("Get Data");
        BtnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDbUpdateLayout = new javax.swing.GroupLayout(PanelDbUpdate);
        PanelDbUpdate.setLayout(PanelDbUpdateLayout);
        PanelDbUpdateLayout.setHorizontalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrlPaneOptionDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                        .addComponent(LblSections)
                                        .addGap(18, 18, 18)
                                        .addComponent(CbxSections, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                        .addComponent(LblOptionName)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ScrlBarOption, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                        .addComponent(LblOptions)
                                        .addGap(18, 18, 18)
                                        .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                        .addComponent(LblAction)
                                        .addGap(25, 25, 25)
                                        .addComponent(CbxAction, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addComponent(LblOptionDescr)
                                .addGap(109, 109, 109))))
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        PanelDbUpdateLayout.setVerticalGroup(
            PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxSections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSections)
                    .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblOptions))
                .addGap(39, 39, 39)
                .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblOptionName)
                                .addComponent(TxtOption, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(ScrlBarOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelDbUpdateLayout.createSequentialGroup()
                        .addGroup(PanelDbUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(LblOptionDescr)))
                .addComponent(ScrlPaneOptionDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnAction)
                .addGap(28, 28, 28))
        );

        PanelMainCards_FrmAdmin.add(PanelDbUpdate, "PanelDbUpdate");

        PanelUserStats.setMinimumSize(new java.awt.Dimension(595, 410));
        PanelUserStats.setPreferredSize(new java.awt.Dimension(595, 410));

        BtnPrev_FrmAdmin.setText("Prev.");
        BtnPrev_FrmAdmin.setName(""); // NOI18N

        BtnView_FrmAdmin.setText("View Statistics");
        BtnView_FrmAdmin.setName(""); // NOI18N
        BtnView_FrmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnView_FrmAdminActionPerformed(evt);
            }
        });

        BtnNext_FrmAdmin.setText("Next");
        BtnNext_FrmAdmin.setName(""); // NOI18N

        ScrlPaneTbUsers.setPreferredSize(new java.awt.Dimension(195, 64));

        TbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbUsers.setMinimumSize(new java.awt.Dimension(195, 64));
        TbUsers.setName(""); // NOI18N
        TbUsers.setPreferredSize(new java.awt.Dimension(195, 64));
        ScrlPaneTbUsers.setViewportView(TbUsers);

        javax.swing.GroupLayout PanelUserStatsLayout = new javax.swing.GroupLayout(PanelUserStats);
        PanelUserStats.setLayout(PanelUserStatsLayout);
        PanelUserStatsLayout.setHorizontalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserStatsLayout.createSequentialGroup()
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BtnPrev_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BtnView_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(BtnNext_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUserStatsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        PanelUserStatsLayout.setVerticalGroup(
            PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserStatsLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(ScrlPaneTbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrev_FrmAdmin)
                    .addComponent(BtnView_FrmAdmin)
                    .addComponent(BtnNext_FrmAdmin))
                .addGap(40, 40, 40))
        );

        PanelMainCards_FrmAdmin.add(PanelUserStats, "PanelUserStats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainCards_FrmAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtnExit_FrmAdmin)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    


    //BUTTON EXIT
    //
    private void BtnExit_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit_FrmAdminActionPerformed
        config = new FrmAdminConfig();
        config.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_BtnExit_FrmAdminActionPerformed

    private void CbxSearchParamsOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSearchParamsOptionsActionPerformed
        this.TxtSearchParamOptions.setEnabled(true);
    }//GEN-LAST:event_CbxSearchParamsOptionsActionPerformed

    private void CbxFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxFieldsActionPerformed
        
        String item = this.CbxFields.getSelectedItem().toString();
        switch(item)
        {
            case "Age":
                
                break;
                    
        
        
        }    
    }//GEN-LAST:event_CbxFieldsActionPerformed

    private void TxtAgeValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue2ActionPerformed

    private void CbxAgeOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxAgeOptionsActionPerformed
        


        
        
        String text = this.CbxAgeOptions.getSelectedItem().toString();
        switch (text)
        {
            case "Equal to":
                this.TxtAgeEqualTo.setEnabled(true);
                
                this.LblAgeEqualTo.setEnabled(true);
                this.LblAgeGreaterThan.setEnabled(false);
                 this.LblAgeLesserThan.setEnabled(false);
                 this.LblAgeRange.setEnabled(false);
                
                
                this.TxtAgeGreaterThan.setEnabled(false);
                this.TxtAgeLesserThan.setEnabled(false);
                this.TxtAgeValue1.setEnabled(false);
                this.TxtAgeValue2.setEnabled(false);
                break;
            case "Greater than":
                this.TxtAgeGreaterThan.setEnabled(true);
                this.LblAgeGreaterThan.setEnabled(true);
                
                this.LblAgeLesserThan.setEnabled(false);
                 this.LblAgeRange.setEnabled(false);
                this.LblAgeRange.setEnabled(false);
                 
                this.TxtAgeEqualTo.setEnabled(false);
                this.TxtAgeLesserThan.setEnabled(false);
                this.TxtAgeValue1.setEnabled(false);
                this.TxtAgeValue2.setEnabled(false);
                break;
            case "Lesser than":
                this.TxtAgeLesserThan.setEnabled(true);
                this.LblAgeLesserThan.setEnabled(true);
        
                this.LblAgeEqualTo.setEnabled(false);
                this.LblAgeGreaterThan.setEnabled(false);
                this.LblAgeRange.setEnabled(false);
                
                this.TxtAgeEqualTo.setEnabled(false);
                this.TxtAgeGreaterThan.setEnabled(false);
                this.TxtAgeValue1.setEnabled(false);
                this.TxtAgeValue2.setEnabled(false);
                break;
            case "Range":
                this.TxtAgeValue1.setEnabled(true);
                this.TxtAgeValue2.setEnabled(true);
                this.LblAgeRange.setEnabled(true);

                 this.LblAgeEqualTo.setEnabled(false);
                this.LblAgeGreaterThan.setEnabled(false);
                 this.LblAgeLesserThan.setEnabled(false);
                
                this.TxtAgeEqualTo.setEnabled(false);
                this.TxtAgeGreaterThan.setEnabled(false);
                this.TxtAgeLesserThan.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_CbxAgeOptionsActionPerformed

    private void TxtSearchParamOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchParamOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchParamOptionsActionPerformed

    
    
    private void BtnInsParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsParamActionPerformed
        String field, search, text;
        
        field = this.CbxFields.getSelectedItem().toString();
        
        
        this.ListParams.setModel(listModel);
        listModel.addElement(field);
        if(RBtnDefine.isSelected() == true)
        {    
            search = this.CbxSearchParamsOptions.getSelectedItem().toString();
            text = this.TxtSearchParamOptions.getText();
            switch (search)
            {
                case "Begin with":
                    params = text + "%";
                    break;
                case "Contain":
                    params = "%" + text + "%";
                    break;
                case "End with":
                    params = "%" + text;
                    break;
            }
        }
        else if(RBtnManual.isSelected() == true)
        {
            
            params = this.TxtParamValue.getText();
        }
        
        
        this.BtnInsParam.setEnabled(false);
    }//GEN-LAST:event_BtnInsParamActionPerformed

    private void TxtAgeValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeValue1ActionPerformed

    private void BtnView_FrmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnView_FrmAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnView_FrmAdminActionPerformed

   
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //COMBOBOX AZIONE
    //
    private void CbxActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxActionActionPerformed
        if(this.CbxAction.isPopupVisible() == true)
        {
            String caption = this.CbxAction.getSelectedItem().toString();
            this.BtnAction.setText(caption);
            this.BtnAction.setEnabled(true);
        }
    }//GEN-LAST:event_CbxActionActionPerformed

    private void CbxActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxActionMouseClicked

    }//GEN-LAST:event_CbxActionMouseClicked

    private void CbxActionPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbxActionPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxActionPopupMenuWillBecomeInvisible

    private void CbxSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSectionsActionPerformed
        this.CbxOption.removeAllItems();
        this.CbxOption.setEnabled(false);
        this.CbxAction.removeAllItems();
        this.CbxAction.setEnabled(false);
        this.BtnAction.setText("Get Data");
        this.TxtOption.setText(null);
        this.BtnAction.setEnabled(true);
        this.TxtOptionDescr.setText(null);
        if(this.ScrlBarOption.isVisible() == true){this.ScrlBarOption.setVisible(false);}
    }//GEN-LAST:event_CbxSectionsActionPerformed

    //COMBOBOX OPTIONS
    //
    private void CbxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxOptionActionPerformed
        if(this.CbxOption.isPopupVisible() == true)
        {
            this.BtnAction.setEnabled(false);
            this.BtnAction.setText("Action");
            this.TxtOption.setText(this.CbxOption.getSelectedItem().toString());
            
           
            
            int vista = 22;
        int count = this.TxtOption.getText().length();
       if (count>vista){this.ScrlBarOption.setVisible(true);}
        else { if (count<vista){this.ScrlBarOption.setVisible(false);}}
            this.CbxAction.setEnabled(true);
            //Sets the combobox with the list of the possible actions
            this.CbxAction.removeAllItems();
            this.CbxAction.addItem("Delete");
            this.CbxAction.addItem("Insert");
            this.CbxAction.addItem("Update");

            
            
            descr = sectionList.get(0).get(this.CbxOption.getSelectedItem().toString());
            this.TxtOptionDescr.setText(descr);
        }
    }//GEN-LAST:event_CbxOptionActionPerformed

    private void CbxOptionPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbxOptionPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxOptionPopupMenuWillBecomeVisible

    private void TxtOptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtOptionKeyReleased
         
    }//GEN-LAST:event_TxtOptionKeyReleased

    private void TxtOptionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TxtOptionPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtOptionPropertyChange

    private void BtnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActionActionPerformed
        try
        {
            String text = this.BtnAction.getText();
            switch (text)
            {
                case "Get Data":
                    String table = this.CbxSections.getSelectedItem().toString();
                    this.CbxOption.removeAllItems();
                    PreparedStatement a = query.selectAll(table);
                    rs = query.execute(a);
                    //          this.CbxOption.setEnabled(true);
                    while(rs.next())
                    {

                        String option = rs.getString(2);
                        this.descr = rs.getString("descr");
                        section.put(option, descr);
                        System.out.println(option + "    " + descr);
                        this.CbxOption.addItem(option);

                    }
                    rs.close();
                    this.CbxOption.setEnabled(true);
                    sectionList.add(0, (HashMap<String, String>) section);
                    System.out.println();
                    System.out.println();
                    for(int i=0; i<sectionList.size(); i++)
                    {//sectionList.get(i);//.get(this.CbxOption.getSelectedItem().toString());
                        }
        System.out.println();
                    break;
                
                case "Delete":
                    String asdf = "SELECT * FROM category;";
                    //PreparedStatement a = query.selectAll(table);
                    rs = query.wtfQuery(asdf);
                    while(rs.next())
                    {
                        System.out.println(rs.getString(1));
                    
                    }
                    break;
                
                case "Insert":
                    String[] prova;
                    try
            {
                prova = query.colTable("user", "findmycareer");
           
//                for(int k =0; k<prova.length; k++)
//                {
//                System.out.println(prova[k]);
//                }
            
            }
            catch(SQLException e){System.out.println("ERRORE!!!!!!!!!!!!!!!!!!!!!!!");}
                    
            
                    break;
                
                case "Update":
                    
                    break;
                
            
            
            }
            
        
        
            
        }
        catch (SQLException ex)
        {
            Logger.getLogger(FrmAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_BtnActionActionPerformed

    private void RBtnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnManualActionPerformed
        card = (CardLayout)this.PanelSetParameterOptions.getLayout();
        card.show(this.PanelSetParameterOptions, "PanelManualParam");
        this.TxtSearchParamOptions.setText(null);
    }//GEN-LAST:event_RBtnManualActionPerformed

    private void RBtnDefineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnDefineActionPerformed
        card = (CardLayout)this.PanelSetParameterOptions.getLayout();
        card.show(this.PanelSetParameterOptions, "PanelDefineParam");
        this.TxtParamValue.setText(null);
    }//GEN-LAST:event_RBtnDefineActionPerformed

    private void BtnRemoveParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveParamActionPerformed
        
        int index = this.ListParams.getSelectedIndex();
        System.out.println(this.ListParams.getModel().getElementAt(index));
        this.ListParams.remove(index);
                //remove(this.listParams.getModel().getElementAt(index).);
        //
    }//GEN-LAST:event_BtnRemoveParamActionPerformed

    private void BtnSeeResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeeResultsActionPerformed
        card = (CardLayout)this.PanelMainCards_FrmAdmin.getLayout();
            card.show(this.PanelMainCards_FrmAdmin, "PanelUserStats");
    }//GEN-LAST:event_BtnSeeResultsActionPerformed

    private void CkbAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkbAgeActionPerformed
        if(this.CkbAge.isSelected() == true)
        {this.CbxAgeOptions.setEnabled(true);}
        else if(this.CkbAge.isSelected() == false)
        {
            this.CbxAgeOptions.setEnabled(false);
            
            this.TxtAgeEqualTo.setEnabled(false);
                
                this.LblAgeEqualTo.setEnabled(false);
                this.LblAgeGreaterThan.setEnabled(false);
                 this.LblAgeLesserThan.setEnabled(false);
                 this.LblAgeRange.setEnabled(false);
                
                
                this.TxtAgeGreaterThan.setEnabled(false);
                this.TxtAgeLesserThan.setEnabled(false);
                this.TxtAgeValue1.setEnabled(false);
                this.TxtAgeValue2.setEnabled(false);
                
                this.TxtAgeGreaterThan.setText(null);
                this.TxtAgeLesserThan.setText(null);
                this.TxtAgeValue1.setText(null);
                this.TxtAgeValue2.setText(null);
            this.TxtAgeEqualTo.setText(null);
            
        }
    }//GEN-LAST:event_CkbAgeActionPerformed

    private void TxtParamValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtParamValueKeyReleased
        if(this.TxtParamValue.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtParamValue.getText().length()==0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtParamValueKeyReleased

    private void TxtSearchParamOptionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSearchParamOptionsKeyReleased
        if(this.TxtSearchParamOptions.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtSearchParamOptions.getText().length()== 0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtSearchParamOptionsKeyReleased

    private void TxtAgeEqualToKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeEqualToKeyReleased
        if(this.TxtAgeEqualTo.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtAgeEqualTo.getText().length()== 0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtAgeEqualToKeyReleased

    private void TxtAgeGreaterThanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeGreaterThanKeyReleased
        if(this.TxtAgeGreaterThan.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtAgeGreaterThan.getText().length()== 0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtAgeGreaterThanKeyReleased

    private void TxtAgeLesserThanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeLesserThanKeyReleased
        if(this.TxtAgeLesserThan.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtAgeLesserThan.getText().length()== 0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtAgeLesserThanKeyReleased

    private void TxtAgeValue1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeValue1KeyReleased
        if(this.TxtAgeValue1.getText().length()>0 && this.TxtAgeValue2.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtAgeValue1.getText().length()== 0 && 
                this.TxtAgeValue2.getText().length()== 0) 
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtAgeValue1KeyReleased

    private void TxtAgeValue2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeValue2KeyReleased
        if(this.TxtAgeValue1.getText().length()>0 && this.TxtAgeValue2.getText().length()>0)
        {this.BtnInsParam.setEnabled(true);}
        else if(this.TxtAgeValue1.getText().length()== 0 && 
                this.TxtAgeValue2.getText().length()== 0)
        {this.BtnInsParam.setEnabled(false);}
    }//GEN-LAST:event_TxtAgeValue2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAction;
    private javax.swing.JButton BtnExit_FrmAdmin;
    private javax.swing.ButtonGroup BtnGroupSetOption;
    private javax.swing.JButton BtnInsParam;
    private javax.swing.JButton BtnNext_FrmAdmin;
    private javax.swing.JButton BtnPrev_FrmAdmin;
    private javax.swing.JButton BtnRemoveParam;
    private javax.swing.JButton BtnSeeResults;
    private javax.swing.JButton BtnView_FrmAdmin;
    private javax.swing.JComboBox CbxAction;
    private javax.swing.JComboBox CbxAgeOptions;
    private javax.swing.JComboBox CbxFields;
    private javax.swing.JComboBox CbxOption;
    private javax.swing.JComboBox CbxSearchParamsOptions;
    private javax.swing.JComboBox CbxSections;
    private javax.swing.JCheckBox CkbAge;
    private javax.swing.JLabel LblAction;
    private javax.swing.JLabel LblAgeEqualTo;
    private javax.swing.JLabel LblAgeGreaterThan;
    private javax.swing.JLabel LblAgeLesserThan;
    private javax.swing.JLabel LblAgeRange;
    private javax.swing.JLabel LblOptionDescr;
    private javax.swing.JLabel LblOptionName;
    private javax.swing.JLabel LblOptions;
    private javax.swing.JLabel LblParamValue;
    private javax.swing.JLabel LblSections;
    private javax.swing.JLabel LblSelectedParams;
    private javax.swing.JList ListParams;
    private javax.swing.JPanel PanelAge;
    private javax.swing.JPanel PanelDbUpdate;
    private javax.swing.JPanel PanelDefineParam;
    private javax.swing.JPanel PanelMainCards_FrmAdmin;
    private javax.swing.JPanel PanelManualInsParam;
    private javax.swing.JPanel PanelSetParameterOptions;
    private javax.swing.JPanel PanelSetParameters;
    private javax.swing.JPanel PanelUserParameters;
    private javax.swing.JPanel PanelUserStats;
    private javax.swing.JRadioButton RBtnDefine;
    private javax.swing.JRadioButton RBtnManual;
    private javax.swing.JScrollBar ScrlBarManual;
    private javax.swing.JScrollBar ScrlBarOption;
    private javax.swing.JScrollBar ScrlBarSearch;
    private javax.swing.JScrollPane ScrlPaneListParams;
    private javax.swing.JScrollPane ScrlPaneOptionDescr;
    private javax.swing.JScrollPane ScrlPaneTbUsers;
    private javax.swing.JTable TbUsers;
    private javax.swing.JTextField TxtAgeEqualTo;
    private javax.swing.JTextField TxtAgeGreaterThan;
    private javax.swing.JTextField TxtAgeLesserThan;
    private javax.swing.JTextField TxtAgeValue1;
    private javax.swing.JTextField TxtAgeValue2;
    private javax.swing.JTextField TxtOption;
    private javax.swing.JTextArea TxtOptionDescr;
    private javax.swing.JTextField TxtParamValue;
    private javax.swing.JTextField TxtSearchParamOptions;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
