package Main;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.ArrayList;


    

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gui Perez
 */
public class FrmEditProfile extends javax.swing.JFrame {
    
    ResultSet rs;
    //Queries query = new Queries();
    Careers careers;
    Connection con = null;
    Statement st;
    ResultSet resultSet;
    FrmLogin frmlogin;
    FrmUserMain frmUserMain;
    String id;
    
    
    String id = frmlogin.id;
    
    Database db = new Database();
    FrmLogin login = new FrmLogin();
    
    /**
     * Creates new form profile
     * @throws java.sql.SQLException
     */
    public FrmEditProfile(){
        this.frmUserMain = new FrmUserMain();
        //this.id = null;
        this.frmlogin = null;
        initComponents();
        careers = new Careers();
        id = frmlogin.getUserID();
        
        System.out.println(id);
    }
    
    private void selectUserByID()
    {
        ArrayList<String> userData = new ArrayList<>();
        String sql = "SELECT password, firstName, lastName, dob, phone, FROM user WHERE userID = "+id+"";
        
        try {
            st = con.prepareStatement(sql);
           // resultSet = st.executeQuery();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
                
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanEditData = new javax.swing.JPanel();
        TxtFirstName = new javax.swing.JTextField();
        LblFirstName = new javax.swing.JLabel();
        TxtLastName = new javax.swing.JTextField();
        LblLastName = new javax.swing.JLabel();
        BtnSaveDetails = new javax.swing.JButton();
        TxtPhone = new javax.swing.JTextField();
        TxtDob = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        LblDob = new javax.swing.JLabel();
        LblPhone = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        BtnCareer = new javax.swing.JButton();
        BtnExit_FrmEditProfile = new javax.swing.JButton();

        jButton2.setText("View Usage Statistics");

        jButton1.setText("View User Careers");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EIDT USER PROFILE");

        PanEditData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        PanEditData.setToolTipText("");
        PanEditData.setName(""); // NOI18N

        LblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblFirstName.setText("First Name:");

        TxtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLastNameActionPerformed(evt);
            }
        });

        LblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblLastName.setText("Last Name:");

        BtnSaveDetails.setText("Save Details");
        BtnSaveDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveDetailsActionPerformed(evt);
            }
        });

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });

        LblDob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDob.setText("DOB:");

        LblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPhone.setText("Phone:");

        LblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblEmail.setText("Email:");

        BtnCareer.setText("View Career Choices");
        BtnCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCareerActionPerformed(evt);
            }
        });

        BtnExit_FrmEditProfile.setText("Exit");
        BtnExit_FrmEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit_FrmEditProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanEditDataLayout = new javax.swing.GroupLayout(PanEditData);
        PanEditData.setLayout(PanEditDataLayout);
        PanEditDataLayout.setHorizontalGroup(
            PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEditDataLayout.createSequentialGroup()
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createSequentialGroup()
                        .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createSequentialGroup()
                                .addComponent(LblLastName)
                                .addGap(19, 19, 19))
                            .addGroup(PanEditDataLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblFirstName)
                                    .addComponent(LblDob)
                                    .addComponent(LblEmail)
                                    .addComponent(LblPhone))
                                .addGap(18, 18, 18)))
                        .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtDob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtLastName)
                                .addComponent(TxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(BtnCareer)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(PanEditDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnSaveDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit_FrmEditProfile)
                .addGap(18, 18, 18))
        );
        PanEditDataLayout.setVerticalGroup(
            PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEditDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFirstName)
                    .addComponent(TxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblLastName)
                    .addComponent(TxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail))
                .addGap(18, 18, 18)
                .addComponent(BtnCareer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSaveDetails)
                    .addComponent(BtnExit_FrmEditProfile))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanEditData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanEditData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLastNameActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void BtnSaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveDetailsActionPerformed
        // TODO add your handling code here:
      this.setVisible(false);
        
//        if(mainFrm == null)
//        {
//            mainFrm = new MainScreen();
//        }
//            mainFrm.setVisible(true);
    }//GEN-LAST:event_BtnSaveDetailsActionPerformed

    private void BtnCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCareerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        if(careers == null)
        {
            careers = new Careers();
        }
            careers.setVisible(true);
    }//GEN-LAST:event_BtnCareerActionPerformed

    private void BtnExit_FrmEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit_FrmEditProfileActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_BtnExit_FrmEditProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCareer;
    private javax.swing.JButton BtnExit_FrmEditProfile;
    private javax.swing.JButton BtnSaveDetails;
    private javax.swing.JLabel LblDob;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFirstName;
    private javax.swing.JLabel LblLastName;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JPanel PanEditData;
    private javax.swing.JTextField TxtDob;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFirstName;
    private javax.swing.JTextField TxtLastName;
    private javax.swing.JTextField TxtPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
