package Main;

//import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;


    

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gui Perez
 */
public class FrmEditProfile extends javax.swing.JFrame {
    
    ResultSet rs; // initialize components
    Connection con = null; // initialize components connection
    PreparedStatement st; // initialize components queries
    
  //  Careers careers= new Careers();
   
    Database db = new Database(); //initialize constructors = Gui
    
    FrmLogin frmlogin = new FrmLogin(); //initialize constructors Login(Yusef) = Gui
    FrmUserMain frmUserMain= new FrmUserMain(); //initialize constructors(Jak)  = Gui
    String id; // access the id on Login form
    
   
    
    /**
     * Creates new form profile
     * @throws java.sql.SQLException
     */
    public FrmEditProfile(){ // start frame with components 
        initComponents();
        
      db.setUser("root"); //setup the connection to the Database = GUi
      db.setPassword(""); //setup the connection to the Database = GUi
      db.setHost("localhost"); //setup the connection to the Database = GUi
      db.setPort("3306"); //setup the connection to the Database = GUi
      db.setDatabase("findmycareer"); //setup the connection to the Database = GUi
        
        try {
            con = db.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
              
        id = frmlogin.getUserID(); // access id in other object PRIVATE FIELD ACCESSED BY STATIC METHOD -- dont forget this 
        
        System.out.println(id);
        
        selectUserByID();
    }
    
    private void selectUserByID() //bring information form the database and fill the fields
    {
       // ArrayList<String> userData = new ArrayList<>();
        String sql = "SELECT password, firstName, lastName, dob, email, phone FROM user WHERE userID = "+id+"";
//          String sql = "SELECT firstName FROM user WHERE userID = "+id+""; // test
//          String sql = "SELECT firstName FROM user WHERE userID =1"; // test
        
        try {
            st = con.prepareStatement(sql);
            rs = st.executeQuery();
            
            while(rs.next())
            {
//                String firstName = rs.getString("firstName"); ///test
//                userData.add(firstName);///test
//                System.out.println(userData.toString());///test

                TxtFirstName.setText(rs.getString("firstName")); //fields
                TxtLastName.setText(rs.getString("lastName")); //fields
                TxtDob.setText(rs.getString("dob")); //fields
                TxtPhone.setText(rs.getString("phone")); //fields
                TxtEmail.setText(rs.getString("email")); //fields
                TxtPassword.setText(rs.getString("password")); //fields
            }
            st.close(); // is in here but i dont know how this works even this is obvious 
            rs.close(); // is in here but i dont know how this works even this is obvious    =/
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    } // end of components
    
    private void updateProfile(){ //update information on the database = Gui
    
        
        String sql = "UPDATE user SET password='"+TxtPassword.getText()+"', firstName='"+TxtFirstName.getText()+"', lastName='"+TxtLastName.getText()+"', dob='"+TxtDob.getText()+"', "
                + "email='"+TxtEmail.getText()+"', phone='"+TxtPhone.getText()+"' WHERE userID= "+id+";";
        
        try {
                System.out.println(sql); // shows the sql on the output of netBeans
                st = con.prepareStatement(sql);
                st.executeUpdate();
                
                st.close(); // is in here but i dont know how this works even this is obvious 
                rs.close(); // is in here but i dont know how this works even this is obvious 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DialogCareer = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        BtnViewCareer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCareerChoice = new javax.swing.JList();
        BtnRemoveCareer = new javax.swing.JButton();
        BtnBackCareer = new javax.swing.JButton();
        PanEditData = new javax.swing.JPanel();
        LblFirstName = new javax.swing.JLabel();
        TxtLastName = new javax.swing.JTextField();
        LblLastName = new javax.swing.JLabel();
        BtnSaveDetails = new javax.swing.JButton();
        TxtPhone = new javax.swing.JTextField();
        TxtDob = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        LblDob = new javax.swing.JLabel();
        LblPhone = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        BtnCareer = new javax.swing.JButton();
        BtnExit_FrmEditProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        TxtFirstName = new javax.swing.JTextField();

        jButton2.setText("View Usage Statistics");

        jButton1.setText("View User Careers");

        DialogCareer.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogCareer.setMaximumSize(new java.awt.Dimension(486, 420));
        DialogCareer.setMinimumSize(new java.awt.Dimension(486, 420));
        DialogCareer.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        DialogCareer.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        DialogCareer.setPreferredSize(new java.awt.Dimension(486, 420));
        DialogCareer.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Career Choices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(202, 24));

        BtnViewCareer.setText("View");
        BtnViewCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewCareerActionPerformed(evt);
            }
        });

        TxtCareerChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(TxtCareerChoice);

        BtnRemoveCareer.setText("Remove");
        BtnRemoveCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveCareerActionPerformed(evt);
            }
        });

        BtnBackCareer.setText("Back");
        BtnBackCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackCareerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnViewCareer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRemoveCareer)))
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnBackCareer))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewCareer)
                    .addComponent(BtnRemoveCareer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBackCareer))
        );

        javax.swing.GroupLayout DialogCareerLayout = new javax.swing.GroupLayout(DialogCareer.getContentPane());
        DialogCareer.getContentPane().setLayout(DialogCareerLayout);
        DialogCareerLayout.setHorizontalGroup(
            DialogCareerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogCareerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        DialogCareerLayout.setVerticalGroup(
            DialogCareerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogCareerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        DialogCareer.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EIDT USER PROFILE");
        setMaximumSize(new java.awt.Dimension(386, 296));
        setMinimumSize(new java.awt.Dimension(386, 296));

        PanEditData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        PanEditData.setToolTipText("");
        PanEditData.setName(""); // NOI18N

        LblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblFirstName.setText("First Name:");

        TxtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLastNameActionPerformed(evt);
            }
        });

        LblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblLastName.setText("Last Name:");

        BtnSaveDetails.setText("Save Details");
        BtnSaveDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveDetailsActionPerformed(evt);
            }
        });

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });

        LblDob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDob.setText("DOB:");

        LblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPhone.setText("Phone:");

        LblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblEmail.setText("Email:");

        BtnCareer.setText("View Career Choices");
        BtnCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCareerActionPerformed(evt);
            }
        });

        BtnExit_FrmEditProfile.setText("Exit");
        BtnExit_FrmEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit_FrmEditProfileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Password:");

        javax.swing.GroupLayout PanEditDataLayout = new javax.swing.GroupLayout(PanEditData);
        PanEditData.setLayout(PanEditDataLayout);
        PanEditDataLayout.setHorizontalGroup(
            PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnSaveDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit_FrmEditProfile)
                .addGap(18, 18, 18))
            .addGroup(PanEditDataLayout.createSequentialGroup()
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanEditDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanEditDataLayout.createSequentialGroup()
                                .addComponent(LblLastName)
                                .addGap(19, 19, 19))
                            .addGroup(PanEditDataLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblFirstName)
                                    .addComponent(LblDob)
                                    .addComponent(LblEmail)
                                    .addComponent(LblPhone)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)))
                        .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(TxtDob)
                                .addComponent(TxtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtEmail)
                                .addComponent(TxtLastName))
                            .addComponent(TxtFirstName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanEditDataLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(BtnCareer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        PanEditDataLayout.setVerticalGroup(
            PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanEditDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFirstName)
                    .addComponent(TxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblLastName)
                    .addComponent(TxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCareer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PanEditDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSaveDetails)
                    .addComponent(BtnExit_FrmEditProfile))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanEditData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanEditData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLastNameActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void BtnSaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveDetailsActionPerformed
        // TODO add your handling code here:
      this.setVisible(false);
        
      
        updateProfile(); // call the query to save on the database
        if(frmUserMain == null) // start to go back to UserMain
        {
            
            frmUserMain = new FrmUserMain(); //initilize the constructor FrmUserMain
            
        }
            frmUserMain.setVisible(true); // go back to UserMain
    }//GEN-LAST:event_BtnSaveDetailsActionPerformed

    private void BtnCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCareerActionPerformed
        // TODO add your handling code here:
        
        this.DialogCareer.setLocationRelativeTo(this.DialogCareer.getParent()); //format position 
        
        this.DialogCareer.setVisible(true);
        
//        TxtCareerChoice.setT("");
        
        String selectCareerTable = "Select * FROM career WHERE userID= '"+id+"'";
        try {
                
                st = con.prepareStatement(selectCareerTable);
                rs = st.executeQuery();
            
                while(rs.next())
                {
                
                    TxtCareerChoice.setToolTipText(rs.getString(WIDTH));
                
                }
                
        } catch (Exception e) {
        }
        
        
        
        
        //String selectView = 
        
        
        
    }//GEN-LAST:event_BtnCareerActionPerformed

    private void BtnExit_FrmEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit_FrmEditProfileActionPerformed
        // TODO add your handling code here:
        System.exit(0); //finish application
        
    }//GEN-LAST:event_BtnExit_FrmEditProfileActionPerformed

    private void BtnViewCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewCareerActionPerformed
        // TODO add your handling code here:
        
        String selectChoice = TxtCareerChoice.getToolTipText().toString();
        String sql = "SELECT `career`.`codJob`,`career`.`codCourse`,`jobs`.`job`,`jobs`.`descr`,`courses`.`descr`,`courses`.`course` FROM career , `jobs` , `courses` where `career`.`userID` = '"+selectChoice+"';";
        
        try {
                
            st = con.prepareStatement(sql);
            rs = st.executeQuery();
            
            TxtCareerChoice.setToolTipText(rs.getString("career`.`codJob"));
            
            st.close(); // is in here but i dont know how this works even this is obvious 
            rs.close(); // is in here but i dont know how this works even this is obvious    =/
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtnViewCareerActionPerformed

    private void BtnRemoveCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveCareerActionPerformed
        // TODO add your handling code here:
        
        TxtCareerChoice.getSelectedValue();
        String selectChoice = TxtCareerChoice.getToolTipText().toString();
        String sql = "DELETE * FROM career WHERE userID = '"+selectChoice+"'"; 
        try {
                
            st = con.prepareStatement(sql);
            rs = st.executeQuery();
            
            TxtCareerChoice.setToolTipText(rs.getString("career`.`codJob"));
            
            st.close(); // is in here but i dont know how this works even this is obvious 
            rs.close(); // is in here but i dont know how this works even this is obvious    =/
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_BtnRemoveCareerActionPerformed

    private void BtnBackCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackCareerActionPerformed
        // TODO add your handling code here:
        
        this.DialogCareer.setVisible(false); // access the DialogCareer box = SAME FRAME
        
    }//GEN-LAST:event_BtnBackCareerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBackCareer;
    private javax.swing.JButton BtnCareer;
    private javax.swing.JButton BtnExit_FrmEditProfile;
    private javax.swing.JButton BtnRemoveCareer;
    private javax.swing.JButton BtnSaveDetails;
    private javax.swing.JButton BtnViewCareer;
    private javax.swing.JDialog DialogCareer;
    private javax.swing.JLabel LblDob;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFirstName;
    private javax.swing.JLabel LblLastName;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JPanel PanEditData;
    private static javax.swing.JList TxtCareerChoice;
    private javax.swing.JTextField TxtDob;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFirstName;
    private javax.swing.JTextField TxtLastName;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
