/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Donati
 */
public class FrmUserMain1 extends javax.swing.JFrame {
static CardLayout cardLayout;
    static JPanel card;
    
    /**
     * Creates new form FrmUserMain1
     */
    public FrmUserMain1() {
        
        card = new JPanel();
        
        JPanel contentPane = (JPanel)this.getContentPane();
        card.setLayout(cardLayout= new CardLayout());
        card.setLocation(29, 144);
        
        JPanel cardH = new JPanel();
        cardH.setLayout(new GridLayout(2, 1));
        cardH.add(this.PanelCategoryDescr);
        
        card.add("Card H", cardH);
        contentPane.add(card);
        
        
      initComponents();
    }
    
    public Object[][] paneList()
    {
        Object[][] paneList = new Object[][]
        {
            {this.PaneIndustry, 40, 157},
            {this.PanelCategoryDescr, 29, 144},
            {this.PanelCourses, 711, 34},
            {this.PanelJob, 29, 144},
            {this.PanelSkills, 717, 449}
        };
        return paneList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneIndustry = new javax.swing.JPanel();
        LblIndustry = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TxtIndustryDescr = new javax.swing.JTextArea();
        PanelCourses = new javax.swing.JPanel();
        cbxCategories4 = new javax.swing.JComboBox();
        lblCategories2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        BtnCategory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnCourses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnSkills = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnJobs = new javax.swing.JButton();
        cbxCategories = new javax.swing.JComboBox();
        lblCategories = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxCategories1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelSkills = new javax.swing.JPanel();
        CbSkills_JDgCategory1 = new javax.swing.JComboBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListSol_JDgJob3 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        PanelJob = new javax.swing.JPanel();
        cbxCategories3 = new javax.swing.JComboBox();
        lblCategories1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        PanelCategoryDescr = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDescrCategory = new javax.swing.JTextArea();
        LblDescrCategory = new javax.swing.JLabel();

        LblIndustry.setText("Description");

        TxtIndustryDescr.setColumns(20);
        TxtIndustryDescr.setRows(5);
        jScrollPane7.setViewportView(TxtIndustryDescr);

        javax.swing.GroupLayout PaneIndustryLayout = new javax.swing.GroupLayout(PaneIndustry);
        PaneIndustry.setLayout(PaneIndustryLayout);
        PaneIndustryLayout.setHorizontalGroup(
            PaneIndustryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneIndustryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneIndustryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblIndustry)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PaneIndustryLayout.setVerticalGroup(
            PaneIndustryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneIndustryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblIndustry)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 425));
        setPreferredSize(new java.awt.Dimension(580, 425));

        cbxCategories4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategories4ActionPerformed(evt);
            }
        });

        lblCategories2.setText("Courses");

        jLabel9.setText("Description");

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane9.setViewportView(jTextArea6);

        javax.swing.GroupLayout PanelCoursesLayout = new javax.swing.GroupLayout(PanelCourses);
        PanelCourses.setLayout(PanelCoursesLayout);
        PanelCoursesLayout.setHorizontalGroup(
            PanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCoursesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(PanelCoursesLayout.createSequentialGroup()
                        .addComponent(lblCategories2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCategories4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelCoursesLayout.setVerticalGroup(
            PanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCoursesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategories4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategories2))
                .addGap(42, 42, 42)
                .addGroup(PanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCoursesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        BtnCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCategory.setText("Category Description");
        BtnCategory.setFocusable(false);
        BtnCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCategory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCategoryActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnCategory);

        jLabel2.setText("           ");
        jToolBar1.add(jLabel2);

        BtnCourses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCourses.setText("Courses");
        BtnCourses.setFocusable(false);
        BtnCourses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCourses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoursesActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnCourses);

        jLabel3.setText("            ");
        jToolBar1.add(jLabel3);

        BtnSkills.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSkills.setText("Skills");
        BtnSkills.setFocusable(false);
        BtnSkills.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSkills.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSkills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSkillsActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnSkills);

        jLabel4.setText("            ");
        jToolBar1.add(jLabel4);

        BtnJobs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnJobs.setText("Outcomes");
        BtnJobs.setFocusable(false);
        BtnJobs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnJobs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJobsActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnJobs);

        cbxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriesActionPerformed(evt);
            }
        });

        lblCategories.setText("Categories");

        jLabel1.setText("Industries");

        cbxCategories1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INformation Technology" }));
        cbxCategories1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategories1ActionPerformed(evt);
            }
        });

        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);

        jButton2.setText("Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Save to profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CbSkills_JDgCategory1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Skills in Demand", "Essential Employablity Skills" }));
        CbSkills_JDgCategory1.setToolTipText("Choose the kind of skills you want to see");
        CbSkills_JDgCategory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSkills_JDgCategory1ActionPerformed(evt);
            }
        });

        ListSol_JDgJob3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(ListSol_JDgJob3);

        jLabel7.setText("Description");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout PanelSkillsLayout = new javax.swing.GroupLayout(PanelSkills);
        PanelSkills.setLayout(PanelSkillsLayout);
        PanelSkillsLayout.setHorizontalGroup(
            PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSkillsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CbSkills_JDgCategory1, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        PanelSkillsLayout.setVerticalGroup(
            PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSkillsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSkillsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSkillsLayout.createSequentialGroup()
                        .addGroup(PanelSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbSkills_JDgCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        cbxCategories3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategories3ActionPerformed(evt);
            }
        });

        lblCategories1.setText("Jobs");

        jLabel8.setText("Description");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        javax.swing.GroupLayout PanelJobLayout = new javax.swing.GroupLayout(PanelJob);
        PanelJob.setLayout(PanelJobLayout);
        PanelJobLayout.setHorizontalGroup(
            PanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJobLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(PanelJobLayout.createSequentialGroup()
                        .addComponent(lblCategories1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCategories3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelJobLayout.setVerticalGroup(
            PanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJobLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategories3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategories1))
                .addGap(42, 42, 42)
                .addGroup(PanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJobLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        TxtDescrCategory.setColumns(20);
        TxtDescrCategory.setRows(5);
        jScrollPane2.setViewportView(TxtDescrCategory);

        LblDescrCategory.setText("Description");

        javax.swing.GroupLayout PanelCategoryDescrLayout = new javax.swing.GroupLayout(PanelCategoryDescr);
        PanelCategoryDescr.setLayout(PanelCategoryDescrLayout);
        PanelCategoryDescrLayout.setHorizontalGroup(
            PanelCategoryDescrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCategoryDescrLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(PanelCategoryDescrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDescrCategory))
                .addGap(23, 23, 23))
        );
        PanelCategoryDescrLayout.setVerticalGroup(
            PanelCategoryDescrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoryDescrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDescrCategory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addComponent(cbxCategories1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(lblCategories)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCategoryDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCategories1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cbxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategories))
                        .addGap(35, 35, 35)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(20, 20, 20))
                    .addComponent(PanelCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(PanelSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelCategoryDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategories4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategories4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategories4ActionPerformed

    private void cbxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxCategoriesActionPerformed

    private void cbxCategories1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategories1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategories1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Point p = this.PaneIndustry.getLocation();
        this.TxtIndustryDescr.setText(p.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbSkills_JDgCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSkills_JDgCategory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbSkills_JDgCategory1ActionPerformed

    private void cbxCategories3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategories3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategories3ActionPerformed

    private void BtnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCategoryActionPerformed
//        Object[][] obj = this.paneList();
//        JPanel p = (JPanel)obj[0][0];
//        JPanel p1 = (JPanel)obj[1][0];
//        p.setLocation((int)obj[1][1], (int)obj[1][2]);
//        p1.setLocation((int)obj[0][1], (int)obj[0][2]);
//        for(int i=1; i<obj.length; i++)
//        {
//            JPanel p = (JPanel)obj[i][0];
//            p.setLocation((int)obj[i][1], (int)obj[i][2]);
//            p.setVisible(false);
//        }
//        
//        p.setVisible(true);
        
        
        cardLayout.show(card, "Card H");
        
    }//GEN-LAST:event_BtnCategoryActionPerformed

    private void BtnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoursesActionPerformed
//        Object[][] obj = this.paneList();
//        JPanel p = (JPanel)obj[1][0];
//        p.setLocation((int)obj[0][1], (int)obj[0][2]);
//        p.setVisible(true);
//        p = (JPanel)obj[0][0];
//        p.setLocation((int)obj[1][1], (int)obj[1][2]);
//        p.setVisible(false);
//        for(int i=2; i<obj.length; i++)
//        {
//            JPanel pane = (JPanel)obj[i][0];
//            pane.setLocation((int)obj[i][1], (int)obj[i][2]);
//        }
        
        
    }//GEN-LAST:event_BtnCoursesActionPerformed

    private void BtnSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSkillsActionPerformed
//        Point p = this.PanelSkills.getLocation();
//        this.TxtDescrCategory.setText(p.toString());
        
    }//GEN-LAST:event_BtnSkillsActionPerformed

    private void BtnJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJobsActionPerformed
//        Point p = this.PanelJob.getLocation();
//        this.TxtDescrCategory.setText(p.toString());
        
    }//GEN-LAST:event_BtnJobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUserMain1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCategory;
    private javax.swing.JButton BtnCourses;
    private javax.swing.JButton BtnJobs;
    private javax.swing.JButton BtnSkills;
    private javax.swing.JComboBox CbSkills_JDgCategory1;
    private javax.swing.JLabel LblDescrCategory;
    private javax.swing.JLabel LblDescrCategory1;
    private javax.swing.JLabel LblDescrCategory2;
    private javax.swing.JLabel LblIndustry;
    private javax.swing.JList ListSol_JDgJob3;
    private javax.swing.JPanel PaneIndustry;
    private javax.swing.JPanel PanelCategoryDescr;
    private javax.swing.JPanel PanelCategoryDescr1;
    private javax.swing.JPanel PanelCategoryDescr2;
    private javax.swing.JPanel PanelCourses;
    private javax.swing.JPanel PanelJob;
    private javax.swing.JPanel PanelSkills;
    private javax.swing.JTextArea TxtDescrCategory;
    private javax.swing.JTextArea TxtDescrCategory1;
    private javax.swing.JTextArea TxtDescrCategory2;
    private javax.swing.JTextArea TxtIndustryDescr;
    private javax.swing.JComboBox cbxCategories;
    private javax.swing.JComboBox cbxCategories1;
    private javax.swing.JComboBox cbxCategories3;
    private javax.swing.JComboBox cbxCategories4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblCategories1;
    private javax.swing.JLabel lblCategories2;
    // End of variables declaration//GEN-END:variables
}
